### ISSUE TITLE
support tcp syslog

### ISSUE THREAD

**Issue by progrium** [gliderlabs/logspout#1]
The only problem is that using the stdlib syslog package prevents you from changing the syslog tag across writes. That's why right now I Dial once for every message sent over syslog (but it's ok because it's udp). However, TCP would require a persistent connection. 

Perhaps the solution is to vendor and fork the syslog package as it is not that complicated. A patch upstream seems unlikely to be merged because this is a much more uncommon use case (logging on somebody else's behalf).

**Comment by progrium** [comment]
Master supports TCP syslog and can easily support TLS if somebody submits a transport.

**Comment by gtmtech** [comment]
@progrium is there any docs on how to use TCP vs UDP syslog? It seems to UDP by default?

**Comment by djmaze** [comment]
[This one](https://github.com/gliderlabs/logspout/issues/25#issuecomment-93866131) is allegedly working.

**Comment by djmaze** [comment]
@gtmtech With master, better try `syslog+tcp://` as described in #107.

**Comment by gtmtech** [comment]
Thanks I found it in the end. Real shame it doesn't support TLS, I cant use it.

**Comment by progrium** [comment]
It's probably a 20-50 line addition for TLS. Surprised nobody has added it
yet.

On Thu, Aug 6, 2015 at 4:48 AM, Geoff Meakin <notifications@github.com>
wrote:

> Thanks I found it in the end. Real shame it doesn't support TLS, I cant
> use it.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/gliderlabs/logspout/issues/1#issuecomment-128311080>.
>



-- 
Jeff Lindsay
http://progrium.com

**Comment by tmornini** [comment]
This is handled in #116, right?
