### ISSUE TITLE
Using udp for syslog

### ISSUE THREAD

**Issue by ujjwal** [gliderlabs/logspout#101]
```splunkforwarder:
   image: gliderlabs/logspout
   cpu_shares: 128
   restart: always
   volumes:
    - /var/run/docker.sock:/tmp/docker.sock
   command: syslog://splunk.domain.com:514
   environment:
    - HOSTNAME
```

Currently this is my config for my syslog logger. Is there a way to specify using UDP instead?

**Comment by mgood** [comment]
The syslog output already uses UDP by default. Can you clarify what issue you're experiencing?

**Comment by ujjwal** [comment]
If my syslog server goes away or experiences an outage - will this continue running the container uninterrupted? 

I see my container shut down if my host is unreachable, and I am guessing it is probably using the TCP transport.
