### ISSUE TITLE
DISCUSSION: logspout > AWS CloudWatch Logs

### ISSUE THREAD

**Issue by jlchereau** [gliderlabs/logspout#110]
How about logspout -> syslogd -> CloudWatch Log Agent, that is merging in a single container:
- https://github.com/gliderlabs/logspout
- https://blogs.aws.amazon.com/application-management/post/TxFRDMTMILAA8X/Send-ECS-Container-Logs-to-CloudWatch-Logs-for-Centralized-Monitoring

Has anyone tried it?
Is there any better alternative?

**Comment by progrium** [comment]
Main thing is that logspout is never going to write logs to disk. The way I'd like to see CloudWatch Logs integration is if the logs can be published directly... either if the cloudwatch agent accepts syslog (which I don't believe it does) or if somebody write an adapter that publishes to the API directly.

Alternatively, if somebody wanted to make an rsyslog container that wrote to disk, then logspout could forward to that agent, which could then also run the cloudwatch agent.

**Comment by jlchereau** [comment]
If my understanding is correct, your 2nd paragraph describes https://blogs.aws.amazon.com/application-management/post/TxFRDMTMILAA8X/Send-ECS-Container-Logs-to-CloudWatch-Logs-for-Centralized-Monitoring

**Comment by progrium** [comment]
There you go.

**Comment by jlchereau** [comment]
Thanks.
For your information AWS API is a dead end because of ThrottleException.
Coming from https://github.com/nearform/docker-cloudwatch/issues/2

**Comment by progrium** [comment]
I wouldn't call that a dead end. It just requires batching.

On Mon, Jun 8, 2015 at 10:11 AM, Jacques L. Chereau <
notifications@github.com> wrote:

> Thanks.
> For your information AWS API is a dead end because of ThrottleException.
> Coming from nearform/docker-cloudwatch#2
> <https://github.com/nearform/docker-cloudwatch/issues/2>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/gliderlabs/logspout/issues/110#issuecomment-110032656>
> .
>



-- 
Jeff Lindsay
http://progrium.com

**Comment by bradgignac** [comment]
@jlchereau From what I can tell, the second paragraph in the blog post you linked isn't exactly what you're looking for. It appears they are using supervisord to run both the CloudWatch agent and rsyslog inside a container. While you could pipe logs from the Docker socket -> Logspout -> Syslog + Agent, it seems simpler to go straight through the API. The API documentation make it seem like it should be pretty straight forward to perform in-memory batching of log events before sending them to the API. I'm going to try taking a stab at this tomorrow.

**Comment by progrium** [comment]
That would be great. It's on my list to do myself, but it's unlikely I'll
get to it soon.

On Wed, Jul 8, 2015 at 2:50 PM, Brad Gignac <notifications@github.com>
wrote:

> @jlchereau <https://github.com/jlchereau> From what I can tell, the
> second paragraph in the blog post you linked isn't exactly what you're
> looking for. It appears they are using supervisord to run both the
> CloudWatch agent and rsyslog inside a container. While you could pipe logs
> from the Docker socket -> Logspout -> Syslog + Agent, it seems simpler to
> go straight through the API. The API documentation make it seem like it
> should be pretty straight forward to perform in-memory batching of log
> events before sending them to the API. I'm going to try taking a stab at
> this tomorrow.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/gliderlabs/logspout/issues/110#issuecomment-119711719>
> .
>



-- 
Jeff Lindsay
http://progrium.com

**Comment by jlchereau** [comment]
I have tried batch sizes of 10, 20, 50, 100 and 150 without success: always get a ThrottleException from AWS API.

**Comment by bradgignac** [comment]
@jlchereau I started playing with this when I had a few spare minutes, and while I'm not done, I have made progress. The trick is that you can't just run batches based on the number of log messages. Based on the CloudWatch docs, my batching strategy is:

- Start buffering logs in memory.
- Flush logs when buffer reaches 10,000 messages.
- Flush logs when buffer reaches 1,048,576 bytes.
- Flush logs if no logs have been received in 1 second and the buffer is not empty.

**Comment by jlchereau** [comment]
@bradgignac thank you. I am not confident with this batching strategy because if the container crashes (or is simply restarted because it is bound to other containers within the same AWS ECS service and ECS decides to restart them because one is unhealthy), thousands of log messages might get lost. Unless I have missed something, I would not consider relying on a logging strategy that might dismiss messages before a crash. Therefore it seems that building a reliable logging infrastructure with logspout + AWS cloudwatch might require more development than I intend to commit considering other possible options.

**Comment by bradgignac** [comment]
@jlchereau Worth noting that these options could be tuned. The message limit and byte limit are just the maximum values allowed by the API.

**Comment by bradgignac** [comment]
Also, I think if the container crashes, your biggest concern would not be the in-memory buffer. It would be the logs you miss while the container is down.

**Comment by bradgignac** [comment]
This has been implemented at https://github.com/bradgignac/logspout-cloudwatch. It's still early -- I need to add CI and better documentation, but we're using it in production at Rackspace.

**Comment by progrium** [comment]
Awesome!

**Comment by damianobarbati** [comment]
@jlchereau did you find a solution to post logs to cloudwatch? Or did you opt for another solution?

@bradgignac seems abandoned, correct?

**Comment by jlchereau** [comment]
No need for logspout. Simply printing to stdout in docker containers and redirecting the stdout to cloudwatch.

**Comment by damianobarbati** [comment]
But you aren't you loosing the ability of seeing `docker logs` and `docker service logs` with it?

**Comment by bradgignac** [comment]
@damianobarbati Correct. I no longer use logspout so my implementation is no longer maintained.
