### ISSUE TITLE
Master branch doesn't obey host flag

### ISSUE THREAD

**Issue by LoopLabsInc** [gliderlabs/logspout#111]
I'm starting logspout with the following command:

`docker run -d --name logspout --volume=/var/run/docker.sock:/tmp/docker.sock -h beta gliderlabs/logspout:master syslog://logs.papertrailapp.com:11111`

However, logs are coming into Papertrail tagged with the container ID for each container that logspout is routing for that particular host. The host (-h) flag works on the `latest` tag, however the logspout container dies after some unknown amount of time, thus I've been using `master`, which does not die, but is also now no longer "centralized"

**Comment by progrium** [comment]
Can you explain what you mean by "centralized"?

Better docs coming soon, but this is relevant:
https://github.com/gliderlabs/logspout/blob/master/adapters/syslog/syslog.go#L45

You can set SYSLOG_HOSTNAME to `{{.Hostname}}` to pick up the container hostname. Perhaps that is a more reasonable default given how most people deploy it.

**Comment by jmstone617** [comment]
Will continue this from my personal account :)

By centralized, I just meant that by setting the host flag, I was previously able to see all of the logs from different physical hosts come into a single stream.

Sorry, but I'm not super familiar with go. Does this line say to use the SYSLOG_HOSTNAME or the value set by the -h flag?
`hostname := getopt("SYSLOG_HOSTNAME", "{{.Container.Config.Hostname}}")`

If that's the case, shouldn't the -h flag still be respected in lui of `SYSLOG_HOSTNAME` being set?

**Comment by Rambrant** [comment]
Stumbled on this when I tried to understand why my Logspout changed behaviour

In previous versions we got logs sent using the host name of the Logspout container. Now it uses the  host name of the container it get the logs from. By setting the environment variable SYSLOG_HOSTNAME to the hostname of the Logspout container I get the old behavior back ;-)

If this is a bug or a change in behavior is up to you to decide...

**Comment by ebr** [comment]
just to chime in: for us, this change in behaviour was very welcome, and a big reason for moving to `master` from `v2`. this allows us to filter in Loggly by the hostname of the container that generated the logs. Previously, all log entries would have their `syslog.host` field set to the hostname of the logspout container, which wasn't useful at all.

**Comment by michaelshobbs** [comment]
#181
