### ISSUE TITLE
too many open files

### ISSUE THREAD

**Issue by chenfisher** [gliderlabs/logspout#115]
I keep getting ```syslog: dial udp ...: too many open files``` after logspout runs for awhile.

Any ideas?

**Comment by jason-d-hobbs** [comment]
+1.  Me too.  RHEL 6.6 and Docker 1.5.

**Comment by progrium** [comment]
I image it's creating a new FD and not cleaning up. Will look into it soon unless somebody else does.

**Comment by schmunk42** [comment]
Same here with Docker 1.8.1, Ubuntu.
Does someone have an idea for a workaround, eg. adding a Redis instance?

**Comment by mgood** [comment]
@schmunk42 what version are you using? I think this was a bug with opening redundant UDP connections, but it should be fixed in the master branch. Try using the "gliderlabs/logspout:master" Docker tag.

**Comment by schmunk42** [comment]
I was using `latest`.
I am using this setup with redis now: https://github.com/rtoma/logspout-redis-logstash
It's working great so far.

**Comment by michaelshobbs** [comment]
I believe this has been resolved. If you find otherwise, please comment and we'll re-open the issue.
