### ISSUE TITLE
TLS Support

### ISSUE THREAD

**Issue by compactcode** [gliderlabs/logspout#116]
I noticed logspout doesn't have tls support and was considering submitting an implementation. I had two questions.

- Are there any reasons why using logspout with tls might be a bad idea? 
- Are you aware of any tricky issues that need to be tackled in order to implement this?

Thanks,
Shanon

**Comment by progrium** [comment]
Given the transport system and Go's TLS library support, implementing would be trivial. What adapter did you want to use TLS with?

**Comment by compactcode** [comment]
Thanks for the quick reply, sounds encouraging. I would like to use the syslog adapter.

**Comment by gtmtech** [comment]
Just started to work with logspout and this was my first question. +1 for TLS support

**Comment by xiaods** [comment]
+1 for TLS support

**Comment by bgoldman** [comment]
I can't get this working. Can you add to the documentation to explain how to use TLS with logspout?

**Comment by afefelov** [comment]
+1 for documentation
