### ISSUE TITLE
logspout linked to another container

### ISSUE THREAD

**Issue by fastmap22** [gliderlabs/logspout#122]
Not an issue ... Looking for best practices.

What is the best way for logspout to send output to another container using only linking...

on CoreOS...

docker run -h %H -e DEBUG=true --link mycontainer:mycontainer --name logspout --volume=/var/run/docker.sock:/tmp/docker.sock gliderlabs/logspout:master raw+tcp://${MYCONTAINER_PORT_19000_TCP_ADDR}:${MYCONTAINER_PORT_19000_TCP_PORT}

will not work as systemd does not replace MYCONTAINER_PORT_19000_TCP_ADDR and MYCONTAINER_PORT_19000_TCP_PORT. 

These, env variables, due to linking, however are available inside the container.

I do not want to expose the port on the host.

**Comment by mgood** [comment]
Links create an entry in /etc/hosts, so you can just use `mycontainer` as the host name instead of the environment variable. E.g. `raw+tcp://mycontainer:19000` should work for your example.

**Comment by michaelshobbs** [comment]
do we think it's necessary to document a docker feature here?

**Comment by gbolo** [comment]
closing this issue, as it is not related to `logspout`.

if you want two or more containers to talk internally without exposing a port, then try creating a new docker bridge network and the containers will automatically be able to resolve each other by container name.
