### ISSUE TITLE
long messages not being logged

### ISSUE THREAD

**Issue by pmvieira** [gliderlabs/logspout#123]
we are logging long messages with 10000 characters+ and we are not seeing them reaching our papertrail logs.
At this stage I am unsure if this would be a problem with either logspout or papertrail.
Is there any limitation on logspout regarding the size of each log line?

Thanks for your help!

**Comment by stuart-warren** [comment]
It's a limitation in papertrails use of the UDP transport http://help.papertrailapp.com/kb/configuration/troubleshooting-remote-syslog-reachability/

**Comment by pmvieira** [comment]
Thanks Stuart! :)

All the best!
