### ISSUE TITLE
question: v3?

### ISSUE THREAD

**Issue by krancour** [gliderlabs/logspout#124]
@progrium I'm curious how close you might be to a v3.  master seems pretty stable to me, but you'd know better than I.

I ask because I'm absolutely loving how what you've got in master and love even more that it's extensible without any need to fork.  Ideally, in the Deis project, we'd like to start using upstream `logspout` (rather than our super old fork of it), paired with a `logspout-v3-deis` module I am cooking up.

Obviously, we don't get deterministic builds of `deis-logspout` if they're `FROM gliderlabs/logspout:master`-- which is why I ask about v3.

Thanks in advance for any and all info!

**Comment by progrium** [comment]
If you want to stage it with a PR we can cut a release. Make sure changelog is right, fix version file, open PR into master, then when that's merged, open a PR from master to release. When the release PR is merged, it will trigger a release.

**Comment by krancour** [comment]
@progrium thanks!  If you think you're in a releasable state, I'll do that.  Look for it in the next couple days.

**Comment by krancour** [comment]
@progrium I started looking at this, but v3 is a major (and awesome) refactor... even browsing through all the commits since v2, I don't feel like I have a complete, yet succinct understanding of the highlights that should be mentioned in the changelog.

**Comment by progrium** [comment]
Fair. Just a lot of other things pulling at me at the moment.
