### ISSUE TITLE
Logspout does not reconnect

### ISSUE THREAD

**Issue by PavelVanecek** [gliderlabs/logspout#125]
This is a duplicate of https://github.com/looplab/logspout-logstash/issues/7

I have a logspout - logstash setup. All works fine, but restarting logstash stops all logs until logspout is restarted too. How can I make it reconnect? Or even find out the cause?

**Comment by sqdk** [comment]
I have the same problem, but with the syslog adapter.

Would be neat if any of the devs could point to a place in the code where these disconnects might happen. I'll make a PR if i get it fixed.

**Comment by mahnunchik** [comment]
+1

**Comment by hotstepper13** [comment]
If you using docker linking to connect logspout to logstash the problem isnt at logspout.
We have had a similar setup and discovered the same error between logstash and elasticsearch. Therefore we switched to "real" networking where we pass the syslog url into the container. If logstash dies (or will be restarted) the connection will be reestablished.

**Comment by michaelshobbs** [comment]
This looks like it's been fixed (mostly).
