### ISSUE TITLE
Allow structured data

### ISSUE THREAD

**Issue by charlesmarshall** [gliderlabs/logspout#13]
Allow the inclusion of structured header data to be compatible with packages such as loggly that require auth tokens and similar inside the syslog header:

see https://www.loggly.com/docs/streaming-syslog-without-using-files/ for an example of headers

**Comment by linuskendall** [comment]
Seems like the latest merge (#20) hasn't propagated to Docker Hub? When I pull the image from there it simply drops/ignores structured_data. Whereas the https://github.com/everydayhero/logspout fork works from the repo and keeps it.

**Comment by progrium** [comment]
Should be in master and soon in latest.
