### ISSUE TITLE
Error starting

### ISSUE THREAD

**Issue by jbaramidze** [gliderlabs/logspout#131]
I'm having trouble starting logspout container, here's the log:

  # logspout v3-master by gliderlabs
 # adapters: syslog raw tls udp tcp
 # options : persist:/mnt/routes
 # jobs    : pump http[logs,routes]:80
 # routes  :
 #   ADAPTER	ADDRESS		CONTAINERS	SOURCES	OPTIONS
 #   syslog	192.168.3.2:514				map[]
2015/09/10 12:01:01 pump: use of closed network connection

I downloaded source and I'm building docker container myself here

**Comment by DirkLachowski** [comment]
Same problem here. I can start logspout's container and after that restart it about two times. After that, only a reboot of the host untangles the network problem.

**Comment by michaelshobbs** [comment]
What command are you using to start the container and have you tried the latest version?

**Comment by josegonzalez** [comment]
Closing as there hasn't been any movement in a few months.
