### ISSUE TITLE
Usage of TLS

### ISSUE THREAD

**Issue by robertjustjones** [gliderlabs/logspout#133]
I see TLS got implemented in #116, but I don't see any indication of how to use it. I would expect to need to specify options like pem file and auth mode like [here](http://help.papertrailapp.com/kb/configuration/encrypting-remote-syslog-with-tls-ssl/#rsyslog).  Any pointers?

**Comment by progrium** [comment]
My bad for not getting @compactcode to document it ...

**Comment by jmagnusson** [comment]
I would love to find out how to do this. Sending sensitive log data without encryption feels pretty scary...

**Comment by bgoldman** [comment]
I'm also having trouble using TLS. I thought it would be as simple as doing `syslog+tls://uri` instead of doing `syslog://uri` but that doesn't work.

I also can't get `syslog+tcp://uri` to work.

What is the correct way to do this?

**Comment by compactcode** [comment]
Have you tried syslog+udp?

I don't have any go experience but it looks like the syslog transport is currently hardcoded to use udp:

https://github.com/gliderlabs/logspout/blob/master/adapters/syslog/syslog.go#L34

**Comment by bgoldman** [comment]
@compactcode Nevermind, I got it to work. I was using the wrong logspout version :)

**Comment by Dynom** [comment]
@bgoldman So what is the correct approach using TCP+TLS?

**Comment by marcusmyers** [comment]
+1 for usage docs

**Comment by dan-compton** [comment]
@Dynom @marcusmyers tls is supported in master.  If you're trying to do what @bgoldman was doing then it's literally:

> syslog+tls://uri

Just make sure that you're pulling from gliderlabs/logspout:master rather than gliderlabs/logspout:latest as :latest now points to release

**Comment by Dynom** [comment]
Excellent @dan-compton, thanks.

**Comment by jmagnusson** [comment]
@dan-compton Will `syslog+tls://uri` use TCP or UDP?

**Comment by dan-compton** [comment]
@jmagnusson 

https://github.com/gliderlabs/logspout/blob/master/transports/tls/tls.go#L25

**Comment by mc0e** [comment]
+1 for usage docs

Actually, go a step further.  The README documents how to send via syslog to `syslog://logs.papertrailapp.com:55555`, without encryption.  This is inappropriate, so just put the `syslog+tls://uri` bit into the docs there.  If you also want to document the unencrypted transport, do it with an appropriate warning.

**Comment by pporada-gl** [comment]
I am starting the logspout container as follows
```
docker run -d \
    --volume=/var/run/docker.sock:/var/run/docker.sock \
    -e SYSLOG_STRUCTURED_DATA="MYAPIKEYSHOULDGOHERE@41058 tag=\"logspout\"" \
    gliderlabs/logspout:master \
    syslog+tls://logs-01.loggly.com:6514
```

When I try to send a message to loggly, I receive
```
0fbasdf5df02        gliderlabs/logspout:master                     "/bin/logspout syslog"   55 minutes ago      Exited (1) 55 minutes ago                                                                               logspout

[root@ip-x-x-x-x ~]# docker logs 0fba
# logspout v3.2-dev by gliderlabs
# adapters: syslog tcp udp tls raw
# options : persist:/mnt/routes
!! x509: certificate signed by unknown authority
```

This may be a Loggly issue, but how can I put my certs into logspout so this handshake completes successfully?

**Comment by josegonzalez** [comment]
@mc0e pull requests welcome.
