### ISSUE TITLE
syslog: dial udp: lookup logs3.papertrailapp.com: Try again

### ISSUE THREAD

**Issue by intellix** [gliderlabs/logspout#135]
It seems like my logspout container is always dead. It only ever seems to run for about 5 minutes before exiting. 

I'm seeing logs delivered to papertrail during this time, so it seems to be correctly setup. It looks like a network hiccup which kills the container. Shouldn't it just retry when it fails to connect?

**Comment by meonkeys** [comment]
@intellix did you find a fix for this?

Also, have you seen #150?

**Comment by michaelshobbs** [comment]
I think this has been fixed for the most part in v3. Please try it out and report back.
