### ISSUE TITLE
Connection Reset By Peer

### ISSUE THREAD

**Issue by jgallen23** [gliderlabs/logspout#136]
I'm running exactly how the readme says:

```
15:18 $ docker run -d --name="logspout" \
>     --volume=/var/run/docker.sock:/tmp/docker.sock \
>     --publish=127.0.0.1:8000:80 \
>     gliderlabs/logspout
664111310c88bb3f010dd9f887507de4dc908f2bc8d81c61bc57debc8c3a2dba
```

and then I get connection reset by peer:

```
15:18 $ curl http://127.0.0.1:8000/logs
curl: (56) Recv failure: Connection reset by peer
```

What other information can I provide to help debug?

**Comment by martinhynar** [comment]
I faced exactly the same problem. Logspout inside container is attached to port 8000 so `--publish=127.0.0.1:8000:8000` should do the trick.
