### ISSUE TITLE
JSON log format with metadata

### ISSUE THREAD

**Issue by ghost** [gliderlabs/logspout#138]
It would be extremely useful to be able to tell logstash to send out it's logs in JSON with the docker hostname/image name/container name:tag/labels attached. If I'm running say 30 docker hosts with Mesos this would let me track down issues and plays very nicely with the json filter in Logstash.

**Comment by diranged** [comment]
+1 .. our entire structure log infrastructure is JSON based. JSON logs would make all of our logs structured automatically and vastly easier to parse!

**Comment by mahnunchik** [comment]
+1

**Comment by dheeraju** [comment]
+1

**Comment by keis** [comment]
https://github.com/looplab/logspout-logstash does this

on my fork of the above I also have some extra hacks to attach the taskId as set my marathon etc

**Comment by progrium** [comment]
Yeah I'm pretty sure there are a couple JSON based adapters...

On Fri, Jan 22, 2016 at 8:11 AM, David Keijser <notifications@github.com>
wrote:

> https://github.com/looplab/logspout-logstash does this
>
> on my fork of the above I also have some extra hacks to attach the taskId
> as set my marathon etc
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/gliderlabs/logspout/issues/138#issuecomment-173930699>
> .
>



-- 
Jeff Lindsay
http://progrium.com

**Comment by michaelshobbs** [comment]
To clarify, is the goal here to send json formatted logs to syslog and destinations other than logstash?

**Comment by michaelshobbs** [comment]
Changing this to documentation. I'll add an `ADAPTERS.md` file similar to dokku's community plugin doc

**Comment by michaelshobbs** [comment]
This already exists [here](https://github.com/gliderlabs/logspout#third-party-modules)

closing
