### ISSUE TITLE
How is this different from fluentd?

### ISSUE THREAD

**Issue by cggaurav** [gliderlabs/logspout#141]

**Comment by ebr** [comment]
you don't have to change the logging driver. therefore:
 - you can keep using `docker logs` (with fluentd you lose this)
 - configuration is simpler (just run logspout and point to whatever destinations you like)
 - [If container cannot connect to the Fluentd daemon, the container stops immediately](https://docs.docker.com/engine/reference/logging/fluentd/) (this creates a SPOF, not so with logspout)

these may or may not be issues for you; we find logspout to be doing a nice job for us so far.
