### ISSUE TITLE
Detect container rename

### ISSUE THREAD

**Issue by siavashs** [gliderlabs/logspout#144]
logspout does not detect the new container name after it is renamed:
```
compassionate_knuth:  web.1    | info: HTTP GET / url=/, connection=upgrade, host=boer.host.com, x-forwarded-proto=http, x-forwarded-for=10.10.10.10, x-forwarded-port=80, x-request-start=1447862791.577, accept-encoding=gzip, deflate, accept=*/*, user-agent=HTTPie/0.8.0, method=GET, httpVersion=1.1, originalUrl=/, , statusCode=404, responseTime=4
```
We are using dokku and noticed that stoping/starting logspout resolves this issue.

```
~# dokku logspout:stop
04e262444bb7ee254af13cd01d9a5e4e2f79c329eed35c35d2262b8aad2d040b
~# dokku logspout:start
logspout
```
```
logspout:  2015/11/18 16:07:12 loading and persisting routes in /mnt/routes 
logspout:  2015/11/18 16:07:12 logspout v2 serving http on :8000 
logspout:  2015/11/18 16:07:12 routing all to syslog://logs.papertrailapp.com:XXXX
...
boer.web.1:  web.1    | info: HTTP GET / url=/, connection=upgrade, host=boer.host.com, x-forwarded-proto=http, x-forwarded-for=10.10.10.10, x-forwarded-port=80, x-request-start=1447862841.258, accept-encoding=gzip, deflate, accept=*/*, user-agent=HTTPie/0.8.0, method=GET, httpVersion=1.1, originalUrl=/, , statusCode=404, responseTime=2
```
But it would be nice if logspout could automatically detect a container renaming.

**Comment by mhlz** [comment]
I'm also using dokku and encountered this issue. I tried looking into the logspout code, but I have no idea where to even start. I'd love for this to be fixed!

**Comment by michaelshobbs** [comment]
@progrium any thoughts here? I'm running into this too since I've started using logspout in prod. I'm happy to have a go at making this work but not sure where to start. 

Additionally, I could modify dokku-logspout to restart on post-deploy, but does that mean logs would be dropped or does logspout maintain some sort of state as to ship missed logs while it was not running? 😄

**Comment by progrium** [comment]
Also came up in registrator. Both were made before you could rename. Can you see if the Docker event stream publishes an event when renaming? Otherwise this is going to get ugly.

**Comment by michaelshobbs** [comment]
Turns out, yes.

Executing this command:
```
docker rename logspout logspout.old
```

Yields this single event:
```
{
  "Action": "rename",
  "Actor": {
    "Attributes": {
      "image": "gliderlabs/logspout:v3",
      "name": "logspout.old"
    },
    "ID": "db8499bc26911518ce5b418f4ad62269dee0fbd42d91fc7180cb1d62873a2b39"
  },
  "Type": "container",
  "from": "gliderlabs/logspout:v3",
  "id": "db8499bc26911518ce5b418f4ad62269dee0fbd42d91fc7180cb1d62873a2b39",
  "status": "rename",
  "time": 1460657124,
  "timeNano": 1460657124109265751
}
```

**Comment by iloveitaly** [comment]
@michaelshobbs awesome work implementing this fix! Could we cut a new release with this update?

**Comment by michaelshobbs** [comment]
@josegonzalez is working on getting the release process documented and will cut one soon I believe
