### ISSUE TITLE
Double logging or missing logs

### ISSUE THREAD

**Issue by themethod** [gliderlabs/logspout#148]
I have been using logspout containers to send logs to papertrail now for a few months and in general it works great! Except that occasionally a logspout container either:
A) Stops sending logs. no errors or anything, it just goes silent. 
B) Starts double logging. duplicating every log message.

Restarting the container gets things working again, however not being able to rely on consistent logs is really a problem. Is anyone else seeing this? Is there a way to enable more verbose logging of the logspout internals which will provide more details about what I'm seeing. 

I will work on a PR to get this fixed if no one is looking at it yet. Any ideas would be appreciated!

**Comment by beeva-diegogarcia** [comment]
Same here,
Running logsput on Amazon's ECS instances,running it manually it sends the ECS's container agent, but silently drop container logs executed as ECS tasks, although logs can be inspected via curl.

**Comment by Tomdarkness** [comment]
See #120

PR has been open for months now, not sure if project is maintained anymore.

**Comment by evjan** [comment]
Seeing this as well, it stops sending logs from some (new?) containers.
