### ISSUE TITLE
persistent routes

### ISSUE THREAD

**Issue by prees1** [gliderlabs/logspout#149]
Having issues creating routes that are persistent. I have several docker containers that I start with docker-compose, including the logspout container. Our current development setup has one container that acts as a data container. I have the routes on this container at `/mnt/routes`. Alternatively, I have tried a volume on the host with the routes: `host/routes:/mnt/routes`. 

Regardless of the method of persistence, when I use `docker-compose up` to bring up all containers (including logspout), logspout fails to find the routes. (As in a curl request to `/routes` returns `[]`) Manual inspection, shows they are present on disk.

The only insight into this that I have is if I use `docker-compose up` on all containers besides logspout. sleep for 3-5 seconds then `docker-compose up -d logspout` the routes are present (curl returns array of json routes).

I have noticed that if a `POST` is made with a address pointing to a non-existent host, then logspout will ignore it. Is this possibly related?

It would be nice if logspout could be brought up first. to allow it to capture the initial logs from the containers. If containers have problems, a lot of times useful entries are near the beginning.

**Comment by prees1** [comment]
I think what is worth mentioning here is that the host that the routes are going too are actually on another container, a container running splunk. I have feeling the issue is that that container and therefore the host referenced in the routes is not available when logspout goes to add the routes, so it drops them. Adding a sleep lets the splunk container get setup and allow the routes to be properly set.

If this is the case, are there any recommendations on how to properly deal with this?

**Comment by pablogrs** [comment]
I encountered the same issue, but in my the container in the route was running when. Have you found a solution or did the sleep worked? Thanks

**Comment by prees1** [comment]
I actually abandoned logspout in favour of the splunk driver for docker logging.

**Comment by josegonzalez** [comment]
I'm going to close this for now. @pablogrs please open a new issue with details on how you are running logspout, the contents of your volume, etc., and I'll try and take a look.
