### ISSUE TITLE
Duplicate (and partially malformed) timestamp

### ISSUE THREAD

**Issue by Dynom** [gliderlabs/logspout#151]
Hi,

When I run logspout like so (systemd):

```systemd
/usr/bin/docker run\
    --name logspout\
    -v /var/run/docker.sock:/tmp/docker.sock\
    -p ${COREOS_PRIVATE_IPV4}:${SERVICE_PORT}:${SERVICE_PORT}\
    -e "SYSLOG_HOSTNAME=%H"\
    gliderlabs/logspout:master\
    syslog+tls://logsN.papertrailapp.com:12345
```

My logs show like the following in Papertrail:
```
Nov 29 20:31:28 service-7 gatekeeper:  <14>1 2015-11-29T19:31:28Z service-7 gatekeeper 8299 - [] 2015-11-29T19:31:28.360Z - info: [Gatekeeper] Request lifecycle took 2.309ms
```

The part `<14>1 2015-11-29T19:31:28Z service-7 gatekeeper 8299 - [] ` is new since I upgraded from the `:latest` tag (which I did because I wanted TLS support).

The logs are becoming a tad-bit verbose at this point, also I don't understand where it's coming from.

**Comment by Tomdarkness** [comment]
See PR #120

**Comment by Dynom** [comment]
Ah, excellent. Thanks @Tomdarkness
