### ISSUE TITLE
forwarding logs to multiple destinations

### ISSUE THREAD

**Issue by ebr** [gliderlabs/logspout#155]
It is unclear from the documentation whether this is possible. E.g.: I'd like to forward all logs to both Loggly and a homegrown ELK stack. From reading the routes API docs, it sounds like adding multiple routes without specifying any filters should accomplish this, but I'd like to validate the assumption before embarking on this journey.

**Comment by progrium** [comment]
Yep!

On Thu, Jan 14, 2016 at 3:09 PM, Eugene Brodsky <notifications@github.com>
wrote:

> It is unclear from the documentation whether this is possible. E.g.: I'd
> like to forward all logs to both Loggly and a homegrown ELK stack. From
> reading the routes API docs, it sounds like adding multiple routes without
> specifying any filters should accomplish this, but I'd like to validate the
> assumption before embarking on this journey.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/gliderlabs/logspout/issues/155>.
>



-- 
Jeff Lindsay
http://progrium.com

**Comment by ebr** [comment]
:+1: Thank you!! (as well for a lightning-fast response) :D
