### ISSUE TITLE
curl http://127.0.0.1:8000/logs , always gives "curl: (52) Empty reply from server"

### ISSUE THREAD

**Issue by gomzeegautam** [gliderlabs/logspout#156]
I am trying to use Logspout API, to fetch logs from my different containers.

## Following are the steps I did:

Pulled logspout using command: docker pull gliderlabs/logspout:latest

### Created two conatiners :
```
docker run -d ubuntu:14.04 /bin/sh -c "while true; do echo Gautam; sleep 100; done"
docker run -d ubuntu:14.04 /bin/sh -c "while true; do echo Hemant; sleep 100; done"
```
### Later I ran :
```
$ docker run -d --name="logspout" \    --volume=/var/run/docker.sock:/tmp/docker.sock \

    --publish=127.0.0.1:8000:80 \

    gliderlabs/logspout
```

After this when I run $ curl http://127.0.0.1:8000/logs

I always get "curl: (52) Empty reply from server"

I am not sure why I am getting this message, am I doing some wrong step or missing some settings?
Can someone look into this.

My “docker version” is
[11:24] 
Client:
Version:      1.9.1
API version:  1.21
Go version:   go1.4.3
Git commit:   a34a1d5
Built:        Fri Nov 20 17:56:04 UTC 2015
OS/Arch:      darwin/amd64

**Comment by ebr** [comment]
`--publish=127.0.0.1:8000:80 \` should be `--publish=127.0.0.1:8000:8000 \`.

currently you're mapping your host's port 8000 to port 80 in the container, but there's nothing listening on port 80 in the container.

**Comment by ebr** [comment]
argh, in lieu of yet another edit: 
you're pulling `:latest`, which is `v2`. This version indeed exposes port 8000. If you pull `:master`, it will expose port 80 and work as per documentation. (so you're doing everything correctly, just not on the corresponding version of the image).
FWIW, i just upgraded to `v3-master`, and it's great.

**Comment by gomzeegautam** [comment]
@ebr  as per your reply, I changed the command and I am now able to see the logs.
But, I am not able to see previous logs. Why is it so?

**Comment by ebr** [comment]
logspout will not aggregate your logs - it simply collects them from running containers and forwards them in real time to an adapter (most commonly, `syslog`, and in this case - `httpstream`). to see older logs, your options include the good old `docker logs`, or a log aggregation solution, e.g. Logstash (as part of the ELK Stack), Loggly, Sumologic, Logentries, and many others.
