### ISSUE TITLE
Exclude containers by label (feature)

### ISSUE THREAD

**Issue by sshipway** [gliderlabs/logspout#159]
I am using Logspout to capture output on all hosts in our Rancher cluster.  Certaing container stacks need to be excluded, but it is not as easy to add an env var as it is to add a label to a previously defined service stack.

It would be very useful to be able to exclude a container by setting a container label, rather than by using the `LOGSPOUT=exclude` environment variable.  If the name of the label could be configured via an env var on the logspout container, then this would be even better.

Also, if you could specify by *inclusion* instead it would be helpful.

EG, 
`docker run ... -e EXCLUDE=logspout.exclude -e INCLUDE=logspout.include gliderlabs/logspout`

Then containers with the label `logspout.include` would be include, unless they also had the label `logspout.exclude`.  Of course, if not defined, `EXCLUDE` would default to nothing, and `INCLUDE` would default to everything.

**Comment by ebr** [comment]
+1 for this. I'm also using Rancher, and there's currently an issue where cadvisor spams the logs, so as a workaround i'd like to exclude it from logspout temporarily. If implemented as suggested by @sshipway, I'd just add a `--label logspout.exclude= ` to my `docker run` command for the Rancher agent.
