### ISSUE TITLE
Job crash ? Unable to start container

### ISSUE THREAD

**Issue by gitmonster** [gliderlabs/logspout#160]
When i try to start logspout with 

```
docker run -d --name="logspout" \
    --volume=/var/run/docker.sock:/tmp/docker.sock \
    --publish=127.0.0.1:8000:8000 \
    gliderlabs/logspout:master
```

I get the following error: 

```
# logspout v3-master by gliderlabs
# adapters: raw tls udp tcp syslog
# options : persist:/mnt/routes
# jobs    : http[logs,routes]:80 pump
# routes  : none
ended: %!s(<nil>)
```
Obviously a certain job has crashed.
No routes defined so far.

**Comment by rvodden** [comment]
I'm seeing the same problem:

`# logspout v3-master-custom by gliderlabs
# adapters: raw udp syslog logstash
# options : persist:/mnt/routes
# jobs    : pump http[routes,logs]:80
# routes  : none
2016/02/22 08:45:18  ended: %!s(<nil>)`

**Comment by rvodden** [comment]
I'm seeing the same issue:
```
# logspout v3-master-custom by gliderlabs
# adapters: raw udp syslog logstash
# options : persist:/mnt/routes
# jobs    : pump http[routes,logs]:80
# routes  : none
2016/02/22 08:45:18  ended: %!s(<nil>)
```

**Comment by gitmonster** [comment]
anyone?

**Comment by jmprusi** [comment]
same here.. running docker 1.10

**Comment by markhamj** [comment]
What was the resolution to this problem?

**Comment by rvodden** [comment]
I've still not found one. I stopped using logspout.

**Comment by progrium** [comment]
In the examples posted there are no initial routes so it has nothing to do.
Is that intended?

On Wed, Mar 2, 2016 at 11:56 AM, rvodden <notifications@github.com> wrote:

> I've still not found one. I stopped using logspout.
>
> On Tue, 1 Mar 2016 22:00 markhamj, <notifications@github.com> wrote:
>
> > What was the resolution to this problem?
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <
> https://github.com/gliderlabs/logspout/issues/160#issuecomment-190924622>
>
> > .
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/gliderlabs/logspout/issues/160#issuecomment-191350012>
> .
>



-- 
Jeff Lindsay
http://progrium.com

**Comment by michaelshobbs** [comment]
Not sure how to fix but willing to PR if someone wants to point me in the right direction?

@mattaitchison @andyshinn

**Comment by zot24** [comment]
I'm having the same issue @michaelshobbs this is what I'm doing:

I'm using `FROM gliderlabs/logspout:latest` and using the following `modules.go`

```
_ "github.com/gliderlabs/logspout/adapters/raw"
_ "github.com/gliderlabs/logspout/adapters/syslog"
_ "github.com/gliderlabs/logspout/httpstream"
_ "github.com/gliderlabs/logspout/routesapi"
_ "github.com/gliderlabs/logspout/transports/tcp"
_ "github.com/gliderlabs/logspout/transports/udp"
_ "github.com/gliderlabs/logspout/transports/tls"
```

And then basically using the following `docker-compose.yml`

```
version: "2"
services:
  logspout:
    container_name: logspout
    build:
        dockerfile: Dockerfile
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock
    ports:
      - "127.0.0.1:8000:8000"
```

The container do not start and this is the output when you print out the log like `sudo docker logs 7fabb031c742`

```
# logspout v3-custom by gliderlabs
# adapters: tls udp tcp syslog raw
# options : persist:/mnt/routes
# jobs    : pump http[routes,logs]:80
# routes  : none
2016/03/04 12:06:35  ended: %!s(<nil>)
```

Could be the version I'm using? `latest` should I be using the `stable` one?

Hope that help! will be great to know what @mattaitchison and @andyshinn are doing, thanks!

**Comment by zot24** [comment]
I just tested with `master` same result the strange thing is it works today and I was able to see the logs go through when running `curl http://127.0.0.1:8000/logs`

**Comment by YarekTyshchenko** [comment]
Use `v2` tag of the image, It seems that latest version is broken since `18 hours ago`.

```
docker run -d --name=logspout --volume=/var/run/docker.sock:/tmp/docker.sock --publish=0.0.0.0:8000:8000 gliderlabs/logspout:v2
```

**Comment by michaelshobbs** [comment]
The port in master and v3 changed to 80. Use `-p 127.0.0.1:80:8000` to access `http://127.0.0.1:8000/logs`

Also to get it to startup without a destination use something like `syslog://`. It's just looking for some argument. It will throw a connection error but will keep running and you'll still be able to see the log stream locally. 

Still seems like a bug but this is at least a workaround.

**Comment by YarekTyshchenko** [comment]
@michaelshobbs Adding `syslog://` as the last argument gives me these sorts of errors:
```
logspout|2016/03/07 15:15:14 syslog: write udp :0: connection refused
```

**Comment by zot24** [comment]
those the v2 will work with modules? I need to use logstash module

btw @michaelshobbs I couldn't make the v3 work even changing the ports as you mentioned, same error

```
# logspout v3 by gliderlabs
# adapters: tls udp tcp syslog raw
# options : persist:/mnt/routes
# jobs    : http[logs,routes]:80 pump
# routes  : none
2016/03/08 09:44:40  ended: %!s(<nil>)
```

**Comment by zot24** [comment]
is it `route` meant to be `none`?

**Comment by michaelshobbs** [comment]
@zot24 [this](https://github.com/michaelshobbs/dokku-logspout/blob/1d4550d371aa16628ab9aab31e5547056d28ce17/commands#L17-L21) is how i run the container in my [dokku plugin](https://github.com/michaelshobbs/dokku-logspout) without a destination.

```
docker run -d --name="logspout" \
                  --volume=/var/run/docker.sock:/tmp/docker.sock \
                  --publish=127.0.0.1:8000:80 gliderlabs/logspout syslog://
```

**Comment by zot24** [comment]
I have being playing around with this and it seems like I can't not have `logstash` module with for example `httpstream` and that was the issue, I'm using now the `v3` just with `udp` and `logstash` module and it's working despite the fact that I can't debug the logs using `httpstream` but it's fine for know.

Thanks for your help @michaelshobbs

**Comment by mattaitchison** [comment]
@zot24, @gitmonster Can you see if 92e5c79 fixes this issue?

**Comment by gitmonster** [comment]
@mattaitchison this works. thank you

**Comment by gitmonster** [comment]
issue is obviously solved. close.
