### ISSUE TITLE
Routing Various Logs From a Container

### ISSUE THREAD

**Issue by nhproject** [gliderlabs/logspout#164]
Hi,

Let's say I have a container which produces various logs to stdout (log_a, log_b, etc..)
I want to route each log to a different place.
Specifically, I'm using Kafka and I want to route each log to a different topic.

Is such a thing possible, using Logspout?

Thanks!

Nitz

**Comment by cynial** [comment]
+1.

Does anyone has solution?

**Comment by michaelshobbs** [comment]
Have you looked at the routes functionality?

https://github.com/gliderlabs/logspout#create-custom-routes-via-http

**Comment by michaelshobbs** [comment]
Closing due to no response.
