### ISSUE TITLE
Bug in V3: message too long

### ISSUE THREAD

**Issue by davidsansay** [gliderlabs/logspout#167]
My system was working good, and since yesterday that the version 3 was released, I only receive "message too long"

```
2016/03/04 22:59:47 syslog: write udp myip:myport: message too long
```

I tried changing again to the deprecated progrium/logspout, and that works.

**Comment by progrium** [comment]
Can you verify that your messages are in fact not too long for a UDP packet?

**Comment by littonchen** [comment]
Hi porgrium, I was running into the same issue, the error was the only thing reporting to papertrail. Switching to the v2 tag allowed for logging to continue.

**Comment by svsool** [comment]
maybe related https://tools.ietf.org/html/rfc5424#section-6.1

**Comment by progrium** [comment]
Right, that is what I was saying before. I'm not sure what could have changed since v2. Perhaps an upstream library changed something about enforcing these limits. However, without data regarding the size of the packets/messages being sent that worked before and don't now, we can't really confirm that hypothesis...

**Comment by davidsansay** [comment]
Hi Progrium, 

I have seen that if I use the new version locally (ubuntu, docker 1.10) it works fine.
But on aws ecs (amazon linux) it fails even sending a "Hello world" message.
Maybe ecs-agent is sending a huge message and it makes that all the other containers fail sending logs.

**Comment by progrium** [comment]
Yes, that could be. If that's the case, that error shouldn't prevent future
log messages from sending. Somebody should investigate.

On Thu, Mar 17, 2016 at 10:49 AM, David Sangines <notifications@github.com>
wrote:

> Hi Progrium,
>
> I have seen that if I use the new version locally (ubuntu, docker 1.10) it
> works fine.
> But on aws ecs (amazon linux) it fails even sending a "Hello world"
> message.
> Maybe ecs-agent is sending a huge message and it makes that all the other
> containers fail sending logs.
>
> —
> You are receiving this because you commented.
> Reply to this email directly or view it on GitHub
> <https://github.com/gliderlabs/logspout/issues/167#issuecomment-197942408>
>



-- 
Jeff Lindsay
http://progrium.com

**Comment by jmreicha** [comment]
I just ran across this.  Are there any workarounds or updates?  I'm not sure how to test the packet sizes being sent and it seems to only happen periodically.

**Comment by michaelshobbs** [comment]
I've only seen this when the message was in fact not too long according to the syslog spec. Closing for now. We can re-open if folks have more data to contribute to a solution

**Comment by SPodjasek** [comment]
Same thing happens in my setup using logspout+logstash in docker swarm:
```
# logspout v3.3-dev-custom by gliderlabs
# adapters: raw tcp tls udp logstash syslog
# options : persist:/mnt/routes
# jobs    : pump routes http[]:80
# routes  :
#   ADAPTER	ADDRESS				CONTAINERS	SOURCES	OPTIONS
#   logstash+udplogstash.inside.somewhere:5000				map[]
2018/01/23 12:54:35 logstash: could not write:write udp 10.x.x.x:33854->10.x.x.x:5000: write: message too long
```
should I switch to TCP for now?

**Comment by michaelshobbs** [comment]
If the message size is too long for the udp spec, then yes you’ll need to use tcp.
