### ISSUE TITLE
Not sending logs to papertrail as of a few days ago

### ISSUE THREAD

**Issue by paustin01** [gliderlabs/logspout#168]
I've been running `latest` in my dev environments for a while now successfully and as of 3/3/2016 I noticed that we weren't getting any logs in papertrail.  The container is started and I when I do a `docker logs logspout` I see only the below (port changed for posting here).  I see nothing in docker.log or anywhere else.  I tried pulling/running the `v2` tag which works for a time and then ultimately crashes when another container is updated and possibly in other scenarios as well (haven't spent time troubleshooting `v2`...would rather get `v3` working).  Using `docker inspect logspout` I didn't see any obvious config differences between the running `v2` and the nonfunctional `v3`.  Any ideas or how I can further troubleshoot?

```
# logspout v3 by gliderlabs
# adapters: syslog raw tls udp tcp
# options : persist:/mnt/routes
# jobs    : pump http[logs,routes]:80
# routes  :
#   ADAPTER	ADDRESS				CONTAINERS	SOURCES	OPTIONS
#   syslog	logs2.papertrailapp.com:12345				map[]
```

**Comment by littonchen** [comment]
We are running into an identical issue with getting logs in papertrail. Other nodes which are running the older version are still reporting, if anyone else has any additional details, it would be greatly appreciated.

**Comment by paustin01** [comment]
Would it be possible to update the `v2` tagged image in dockerhub with the last version of it prior to the recent `v3` push a few days ago (or tag it separately somehow) at least until there's a resolution/response? Otherwise I'll probably end up building/storing it myself from the last commit on 2/24 which I'd rather not do.  Thanks!

**Comment by progrium** [comment]
There's always a `:master` tag you can use. But I'm not sure I follow your suggestion about updating `v2`...

**Comment by progrium** [comment]
Most importantly I would love to solve this issue and cut a new release.

**Comment by paustin01** [comment]
Sorry I wasn't clear.  I was under the assumption that the image tagged as `:master` was at the same version (or later) as `v3`.  I'm looking whatever was marked as `latest` up until end of last week.  Basically the current `latest` image doesn't work for me and the `v2` image crashes every time I restart another container.  Whatever was marked as `latest` early last week was working perfectly.  Hopefully this makes more sense.  Thanks again.

**Comment by kytwb** [comment]
Same issue here. Anyone knows which tag to use then?

**Comment by littonchen** [comment]
I've been using the v2 tag, haven't seen the same issues that paustin01 has.

**Comment by kytwb** [comment]
Here to confirm it's working with v2.

**Comment by agios** [comment]
Same problem here, using master. Some nodes are working, but the ones that fail have several logs of:

> 2016/03/18 11:56:14 syslog: write tcp xx.xx.xx.xx:yyyy: connection timed out
> 2016/03/18 11:56:14 syslog: retrying tcp up to 11 times
> 2016/03/18 11:56:55 syslog: retry failed
> 2016/03/18 11:56:55 syslog: reconnecting up to 11 times

The message might show up from once every 30 mins to once every 5 hours. However, the node will keep sending logs for a few days and at some point stops, without any other particular error indication - the same error messages continue at a similar rate.

**Comment by dgmstuart** [comment]
Same here - we've been pulling down `latest` on our staging server and our logs stopped working around the 7th of March. 

Initially we got this:
```
# logspout v3 by gliderlabs
# adapters: raw tls udp tcp syslog
# options : persist:/mnt/routes
# jobs    : http[routes,logs]:80 pump
# routes  :
#   ADAPTER ADDRESS         CONTAINERS  SOURCES OPTIONS
#   syslog  xxx.xxx.xxx.x:yyy               map[]
2016/03/14 18:01:36 syslog: write udp xxx.xxx.xxx.x:yyy: connection refused
2016/03/14 18:01:37 syslog: write udp xxx.xxx.xxx.x:yyy: connection refused
```

On restarting logspout we got the same starting comment, but no log entries.

Pulling `v2` seems to work - hopefully it won't crash on us!

**Comment by agios** [comment]
This is odd, I had restarted logspout on 3 vms 10 days ago, sticking with master to possibly help to debug this, yet nothing has failed since...

**Comment by Daniel-ltw** [comment]
```
Apr 11 15:22:02 0ba98c0a6169 logspout:  2016/04/11 15:22:01 syslog: write tcp <ip> -> <papertrail>: write: broken pipe
Apr 11 15:22:02 0ba98c0a6169 logspout:  2016/04/11 15:22:01 syslog: reconnecting up to 11 times
Apr 11 15:37:32 0ba98c0a6169 logspout:  2016/04/11 15:37:32 syslog: write tcp <ip> -> <papertrail>: write: broken pipe
Apr 11 15:37:32 0ba98c0a6169 logspout:  2016/04/11 15:37:32 syslog: reconnecting up to 11 times
Apr 11 15:52:54 0ba98c0a6169 logspout:  2016/04/11 15:52:54 syslog: write tcp <ip> -> <papertrail>: write: broken pipe
Apr 11 15:52:54 0ba98c0a6169 logspout:  2016/04/11 15:52:54 syslog: reconnecting up to 11 times
```

Is this related to this?

**Comment by raj-room** [comment]
We are having problems where logspout occasionally stops sending logs to papertrail. Interestingly, logspout continues to send logs for some containers on a host, even after logs for one container stops showing up in papertrail. This is for a low volume of log lines, using UDP logging on v3. It usually happens after a uptime of > 1 week (for both the logspout container and the application container). 

I can force logspout to stop sending by running load tests that cause a high volume of log lines (>1000/sec). Nothing shows up in the logspout container's log when this happens. I asked papertrail, and they say that their service can handle the volume of logs we are sending and that we are not hitting a limit on their side.

**Comment by MaikuMori** [comment]
Ran into the same issue, logspout containers are still running, but they're not sending any logs.

**Comment by theikkila** [comment]
Same issue here, though not with papertrail.
One of the containers is sending the logs correctly but the other isnt.
Error message in faulty container is:
```
# logspout v3 by gliderlabs
# adapters: raw tls udp tcp syslog
# options : persist:/mnt/routes
# jobs    : http[routes,logs]:80 pump
# routes  :
#   ADAPTER	ADDRESS		CONTAINERS	SOURCES	OPTIONS
#   syslog	10.4.1.142:5555				map[]
2016/04/19 17:29:06 syslog: write udp 10.4.1.142:5555: connection refused
2016/04/19 17:29:10 syslog: write udp 10.4.1.142:5555: connection refused
2016/04/19 17:29:10 syslog: write udp 10.4.1.142:5555: connection refused
2016/04/19 17:29:10 syslog: write udp 10.4.1.142:5555: connection refused
2016/04/19 17:29:10 syslog: write udp 10.4.1.142:5555: connection refused
2016/04/19 17:29:11 syslog: write udp 10.4.1.142:5555: connection refused
2016/04/19 17:29:11 syslog: write udp 10.4.1.142:5555: connection refused
```

version is `gliderlabs/logspout:latest`

**Comment by alexw23** [comment]
This is beginning to become a major pain. Is there any fix in sight for it?

**Comment by michaelshobbs** [comment]
This works for me using `gliderlabs/logspout:v3`.

```
$ docker inspect -f '{{ .Config.Cmd }}' logspout
{[syslog://xxxx.papertrailapp.com:YYYYY]}
```
```
$ docker logs logspout
# logspout v3 by gliderlabs
# adapters: raw tls udp tcp syslog
# options : persist:/mnt/routes
# jobs    : pump http[logs,routes]:80
# routes  :
#   ADAPTER	ADDRESS				CONTAINERS	SOURCES	OPTIONS
#   syslog	xxxx.papertrailapp.com:YYYYY				map[]
```

**Comment by troy** [comment]
I'm with Papertrail. While this isn't Papertrail-specific[1] and I don't know the logspout codebase well,
I skimmed the reconnect logic in `master` and the recent commits. A few things stood out:

* It looks like [this Write call](https://github.com/gliderlabs/logspout/blob/master/adapters/syslog/syslog.go#L97) may be blocking. It may need a call to [SetWriteDeadline](https://golang.org/src/net/net.go#L119), similar to how Papertrail's own [remote_syslog2](https://github.com/papertrail/remote_syslog2) [calls it](https://github.com/papertrail/remote_syslog2/blob/master/syslog/syslog.go#L154)
* the calls to `Dial` ([here](https://github.com/gliderlabs/logspout/blob/master/adapters/syslog/syslog.go#L150), less so [here](https://github.com/gliderlabs/logspout/blob/master/adapters/syslog/syslog.go#L37)) may need a [DialTimeout](https://github.com/papertrail/remote_syslog2/blob/master/syslog/syslog.go#L68) call to make the `Dial` return

Again, I don't know the logspout codebase well, so these may not be problems or may be taken care of somewhere else. I'm trying to do what I can in hopes that it inspires someone who does know the codebase better.

[1]: Syslog clients/senders control reconnect behavior (and some people pasted output from UDP, where the client doesn't even know about reachability). Papertrail is widely used enough that it's often the service which uncovers unexpected behavior in syslog clients.

**Comment by michaelshobbs** [comment]
@paustin01 @alexw23 can you try again with `v3` and confirm this does or does not work? 

also to confirm, do you get any logs to papertrail or do they stop coming in after some time? any additional info to help recreate would be great.

**Comment by agios** [comment]
I'm beginning to suspect this might be a papertrail issue. Stopped receiving logs again a few days ago, after 6 weeks of smooth operation.

However, I've also enabled remote rsyslog on the servers (both tcp with tls), and I've stopped receiving logs from there too. Can anyone else check if this affects only logspout or is more generalized?

**Comment by troy** [comment]
@agios: If you have questions about Papertrail itself, hit up support@ and we'll try to be useful.

(That said, Papertrail is operating normally and, since dozens or hundreds of different syslog implementations send to Papertrail, I can fairly confidently say it's not Papertrail. I don't want to clog this issue with environment-specific troubleshooting, so hit us up at support@ and we'll work with you.)

**Comment by agios** [comment]
@troy I've already raised an issue with support, but there are good indications that this might be a Papertrail issue in our case (or at least not logspout related, since rsyslog stops logging too), which is why I posted, to possibly help others facing the same problem or otherwise identify that our issue is a different case

**Comment by alexw23** [comment]
I've moved to `v3` so I'll report back in a few days.

**Comment by alexw23** [comment]
Is anyone having issues with other providers - i.e. loggly, I would consider switching for now.

**Comment by bobzoller** [comment]
I'm debugging a similar problem and I use Sumo Logic (so I don't think it's provider specific).  I am using a custom build with [logspout-sumo](https://github.com/goodeggs/logspout-sumo), but it is v3 (master as of May 9th).

**Comment by bobzoller** [comment]
I found docker/docker#21220 and am feeling like that could be the root cause of my issue because I run with `--log-opt max-file=2 --log-opt max-size=50m`.

Looking at [router/pump.go#L156](https://github.com/gliderlabs/logspout/blob/master/router/pump.go#L156), it seems if we _did_ hit this issue and the stream closed, logging for that container wouldn't resume until the container restarts or logspout itself does.

Does that sound plausible or am I grokking wrong?  If so, it seems like we need some version of the `docker.Logs` wrapper code as suggested [here](https://github.com/docker/docker/issues/21220#issuecomment-205640044).

**Comment by raj-room** [comment]
Switching from Logspout to the built-in docker syslog driver to send to papertrail has been working without issue for the last month. We don't see issues on papertrail side.

**Comment by alexw23** [comment]
This is an issue with logspout. The logs stopped working and I logged in to HTTP agent on logspout - no logs there either. Other containers are still logging fine. So it looks like an issue with logspout. @raj-room care to show some example code of this?

**Comment by hadara-2016** [comment]
Where does this stand? I'm still having this issue on k8s :\. I've tried master and latest. Still randomly not sending logs.
