### ISSUE TITLE
Support http_proxy env flag

### ISSUE THREAD

**Issue by Khazrak** [gliderlabs/logspout#169]
When doing a custom module build I get stopped by the corporate proxy:

fetch http://alpine.gliderlabs.com/alpine/v3.1/main/x86_64/APKINDEX.tar.gz
ERROR: http://alpine.gliderlabs.com/alpine/v3.1/main: IO ERROR
WARNING: Ignoring APKINDEX.104533ab.tar.gz: No such file or directory

I tested pasting the url in a browser and it downloaded. So my guess is that git/mercurial needs the proxy address (only setting http_proxy won't do it). So maybe script so the http_proxy env variable will be copied to git/mercurial settings?

**Comment by martinbaillie** [comment]
I was able to get around this with build args:
--build-arg=http_proxy=http://<proxy>
--build-arg=https_proxy=https://<proxy>
