### ISSUE TITLE
tag docker images

### ISSUE THREAD

**Issue by defunctzombie** [gliderlabs/logspout#17]
It would be helpful to tag the docker images (maybe with the first 6 characters of the git sha) or a version if you are versioning.

This would allow production users to pin to a specific working release and avoid having the container switch to a possible non-working one if using "latest".

**Comment by progrium** [comment]
Project now has two tags: master and latest. Latest is the latest release, which are tagged Github releases. If you want an old release, you can download and load into Docker directly. Also, anybody can propose a release by opening a PR from master into the release branch. CircleCI will automatically create the release artifacts and it will end up on Docker Hub.
