### ISSUE TITLE
Upgrade Alpine version for faster and more secure GO version

### ISSUE THREAD

**Issue by rtoma** [gliderlabs/logspout#173]
The current Dockerfile is using Alpine Linux 3.1 which was released in 2014-12-10 and bundles golang 1.3.3-r1.

Please use a newer Alpine Linux so Logspout can benefit from a faster and more secure golang version.

**Comment by mattaitchison** [comment]
I'll accept a PR for this if you can make the changes.

**Comment by rtoma** [comment]
Done, please review https://github.com/gliderlabs/logspout/pull/174
