### ISSUE TITLE
Settings hostname for Kubernetes pods

### ISSUE THREAD

**Issue by tspecht** [gliderlabs/logspout#176]
Hey,

I'm running logspout as a DaemonSet inside my Kubernetes cluster. Those containers are successfully set up to send the stdout and stderr from my pods to Papertrail. However when I see the logs coming in the "program" field (e.g. the "name") is pretty verbose and contains a lot of randomly generated UUID on a per-deployment-basis.
Is there any way I could teach logspout to use a static name per pod which I could use?

**Comment by filipegiusti** [comment]
You can pass parameters as in the [routesapi](https://github.com/gliderlabs/logspout/tree/master/routesapi) using query params and set SYSLOG variables as environment variables. So if you want to only collects logs from containers named "application" and marks those in papertail as hostname start logspout container as

	$ docker run --name="logspout" \
		--volume=/var/run/docker.sock:/var/run/docker.sock \
		-e "SYSLOG_HOSTNAME=application" \
		-e "SYSLOG_TAG={{.Container.Config.Hostname}}" \
		gliderlabs/logspout \
		syslog://logs.papertrailapp.com:55555?filter.name=application

Also stay tuned on the PR that [add env vars on SYSLOG_TAG template](https://github.com/gliderlabs/logspout/pull/182).

**Comment by tspecht** [comment]
@filipegiusti thanks for the reply! However I'm afraid this is not going to solve my problem. The underlying cause is that I'm running one logspout containers to collect data from many different applications each running in their own docker-container. Hence if I would do what you suggested I would get all my logs tagged as being from the same application although they are not :(

**Comment by filipegiusti** [comment]
I solved that using namespaces, not sure if that fits your environment.

```yml
        - name: SYSLOG_HOSTNAME
          value: '{{ index .Container.Config.Labels "io.kubernetes.pod.namespace" }}'
```

on that same idea you can set a name per Papertail program as an environment variable as

```yml
        - name: SYSLOG_TAG
          value: '{{ index .Container.Config.Env "PROGRAM_NAME" }}'
```

I spend a lot of time reading logspout source to keep that information to myself. :smile:

**Comment by pstadler** [comment]
In case somebody else is running a Kubernetes cluster using Rancher. The following configuration works well for me:

```
- name: SYSLOG_HOSTNAME
  value: '{{ .Hostname }}'
- name: SYSLOG_TAG
  value: '{{ .Container.Config.Hostname }}'
```

The only issue is that containers deployed by Rancher (e.g. rancher/agent) are logged with their container id instead of a more descriptive name.

**Comment by josegonzalez** [comment]
Seems like there are multiple ways to specify this from your cluster implementation of choice. Closing.

**Comment by mmoore0011** [comment]
syslog: template: syslog:1:67: executing "syslog" at <index .Container.Con...>: error calling index: cannot index slice/array with type string

**Comment by josegonzalez** [comment]
@mmoore0011 if you're filing an issue about a bug, please open a new issue. Do not resurrect an old issue that was closed 2 years ago.
