### ISSUE TITLE
make httpstream module port configurable

### ISSUE THREAD

**Issue by jeroenjacobs1205** [gliderlabs/logspout#178]
Hi,

We are using logspout in docker HOST networking mode (we have a good reason for this, just trust me on this one). Now we run into trouble if we deploy logspout on a webserver (since our nginx listens on port 80, so we get a conflict). Port mappings are not supported in HOST networking mode.

Is there a way to override the port used by the httpstream module? Or disable it via a parameter or commandline parameter?

**Comment by mattaitchison** [comment]
You should be able to change the port by setting `PORT=` or `HTTP_PORT=`.
