### ISSUE TITLE
hostname is not sent correct to papertrail

### ISSUE THREAD

**Issue by tompson** [gliderlabs/logspout#181]
Today I upgraded from `progrium/logspout` to `gliderlabs/logspout` and now I do not get the correct hostname in my papertrail account anymore.

When I run

```
docker run -d  --restart=always --name=logspout --volume=/var/run/docker.sock:/var/run/docker.sock -h $(hostname) progrium/logspout syslog://logs3.papertrailapp.com:12345
```

I get a log looking like

```
Apr 22 10:25:05 nepal test_nginx_1:  nginx.1    | test.example.com 174.34.162.242 - - [22/Apr/2016:10:25:05 +0200] "GET /checkStatus.html HTTP/1.1" 200 14 "-" "Pingdom.com_bot_version_1.4_(http://www.pingdom.com/)" 
```

when I run 

````
docker run -d  --restart=always --name=logspout --volume=/var/run/docker.sock:/var/run/docker.sock -h $(hostname) gliderlabs/logspout syslog://logs3.papertrailapp.com:12345
```

I get 

```
Apr 22 11:04:28 7b9e3e256273 test_nginx_1:  nginx.1    | test.example.com 174.34.162.242 - - [22/Apr/2016:10:25:05 +0200] "GET /checkStatus.html HTTP/1.1" 200 14 "-" "Pingdom.com_bot_version_1.4_(http://www.pingdom.com/)" 
```

So instead of the hostname `nepal` I get `7b9e3e256273`. 

I looked into the logspout container with `docker exec `and the hostname is set correctly there

**Comment by michaelshobbs** [comment]
If I understand the issue correctly, I have gotten around this by setting the container hostname on each of the non-logspout containers themselves.

@progrium @mattaitchison @andyshinn was this change by design?

**Comment by andyshinn** [comment]
According to the code at https://github.com/gliderlabs/logspout/blame/master/adapters/syslog/syslog.go#L44, it would now be the hostname of container (unless overridden by `SYSLOG_HOSTNAME`). To get the previous behavior, set `SYSLOG_HOSTNAME="$(hostname)"`.

**Comment by tompson** [comment]
before it was

`DATE HOSTNAME CONTAINER_NAME`

now it is

`DATE ID CONTAINER_NAME`

I do not want to replace the container name and lose that information but replace the ID with the name of the host my containers are running on

**Comment by michaelshobbs** [comment]
`container_name` != `hostname_of_container`
If I understand correctly @andyshinn's comment would give you want you're wanting. Perhaps, give it a shot and report back?

**Comment by tompson** [comment]
@michaelshobbs sorry, I somehow overlooked that hint

@andyshinn yes, setting die env variable SYSLOG_HOSTNAME="$(hostname)" works, thank you!

**Comment by michaelshobbs** [comment]
No worries. Glad you got it sorted.
