### ISSUE TITLE
logspout does not pickup configurations in /mnt/routes

### ISSUE THREAD

**Issue by mhariri** [gliderlabs/logspout#184]
Logspout ignores the /mnt/routes configuration files sporadically. So when I start it, I get:
```
# logspout v3.1-dev by gliderlabs
# adapters: udp tls raw syslog tcp
# options : debug:true persist:/mnt/routes
# jobs    : http[logs,routes]:80 pump
# routes  : none
2016/04/29 11:56:00  ended: %!s(<nil>)
```

But after restarting the docker container a few times(docker restart logbox_logspout_1), I can see that the logs are picked up:

```
# logspout v3.1-dev by gliderlabs
# adapters: raw syslog tcp udp tls
# options : debug:true persist:/mnt/routes
# jobs    : http[routes,logs]:80 pump
# routes  :
#   ADAPTER     ADDRESS         CONTAINERS      SOURCES OPTIONS
#   syslog+tcp  logstash:5028   *_apxmmn_*              map[]
2016/04/29 11:56:40 pump.pumpLogs(): 819c1c03b09d started
```

I'm using gliderlabs/logspout:master docker image.

**Comment by michaelshobbs** [comment]
Can you provide the docker cmd you used to start the container and how you made your routes available to logspout?

**Comment by mhariri** [comment]
I'm using docker-compose, and this is the section for logspout:

```
logspout:
  image: gliderlabs/logspout
  environment:
    DEBUG: "true"
  volumes:
    - /var/run/docker.sock:/var/run/docker.sock
  links:
     - logstash
  command: syslog://logstash:5000
```

**Comment by mhariri** [comment]
Actually, it this behaviour be a duplicate of #185 , assuming logstash did not start before logspout ...

**Comment by michaelshobbs** [comment]
I've read you can force startup order with docker-compose by using the `volumes_from` directive.

**Comment by mhariri** [comment]
looking at the logs, it only happens in the beginning, not in subsequent restarts in which logstash is running, so counting it as duplicate of #185
