### ISSUE TITLE
logspout container won't start without route configuration

### ISSUE THREAD

**Issue by petestorey26** [gliderlabs/logspout#185]
I'm trying to get started with logspout, but following any of the examples in the readme fails, seemingly because it requires a route to be provided as part of the "run" command when starting the container.

If I don't, I get an error:

```
# logspout v3.1-dev-custom by gliderlabs
# adapters: splunk
# options : debug:1 persist:/mnt/routes
# jobs    : http[logs,routes]:80 pump
# routes  : none
2016/05/01 11:09:30  ended: %!s(<nil>)
```

The problem is I'm trying to connect it to a Splunk server, also in a container, but it means I have to be sure the splunk server has started before logspout, otherwise it will fail.  Any ideas?

**Comment by michaelshobbs** [comment]
I noticed the same thing in the latest release

**Comment by mattaitchison** [comment]
Should be caused by the following. I'll get a fix for it.
https://github.com/gliderlabs/logspout/commit/9dd3277bfa419873dec5ff06a74c28a3ead1edf2#diff-da28fe63f6943ed23c90b01cc3b7565fL169

**Comment by jnardiello** [comment]
I'm having the same issue, having troubles getting started as the binary simply won't start. Any news on this?

**Comment by michaelshobbs** [comment]
Check out my temporary [workaround in dokku-logspout](https://github.com/michaelshobbs/dokku-logspout/blob/2fb84a8b6064f4c7ea7e482c451c87110252486f/commands#L14-L22)

Essentially I always include a `CMD` arg to the `docker run` command even when we don't have a server defined. (i.e. `syslog://`) For the record, I still think this is a bug.

Not sure if this helps your specific issues but that's how I got the container to start for my use case.

**Comment by michaelshobbs** [comment]
23d3c9f seems to remedy the crashing behavior
