### ISSUE TITLE
If you reach papertrail limit all logspout instances exit (crash?).

### ISSUE THREAD

**Issue by MaikuMori** [gliderlabs/logspout#188]
Is this expected behavior? To me it seems more reasonable if it would just resume sending logs when possible.

**Comment by josegonzalez** [comment]
That doesn't sound like it's a good thing to do (the crashing). Do you have a stacktrace?

**Comment by MaikuMori** [comment]
We have since increased the papertrail account limit. Sadly I don't have logs left from that time, but it was consistent on all cluster machines. Every single logspout container exited.

You probably can try to reproduce it with free papertrail account and just filling it up with useless logs until they stop accepting more. At that point it should cause the logspout containers to exit (crash?).

**Comment by michaelshobbs** [comment]
In v3.2.1 logspout should attempt to reconnect up to `RETRY_COUNT`. After that, logspout will shut down. You can keep the container up by using docker's restart policies.
