### ISSUE TITLE
Wrong order on Papertrail, is it because of UDP protocol being used?

### ISSUE THREAD

**Issue by edpichler** [gliderlabs/logspout#194]
The logs appears in wrong order on Papertrail. Is this a limitation? Or it's o configuration problem?

Logs in wrong order are almost useless for erros investigation, unfortunately. Is it possible to logspout container show it in right order?

**Comment by josegonzalez** [comment]
This seems to be a limitation of papertrail - at least according to this [discussion entry](http://help.papertrailapp.com/discussions/problems/2473-strict-log-line-ordering-heroku-drain.html). Not much we can do here if they throw out the timestamp in the syslog message.

**Comment by edpichler** [comment]
Thank you @josegonzalez . So I will talk to them.

**Comment by johlym** [comment]
Hi all, 

Johnathan from Papertrail, here. @edpichler sent us an email and mentioned this issue so I wanted to add some insight.

The timestamp of when the log message was created isn't ultimately thrown out. The timestamp a user sees in PT is when we received the message. Original timestamps (when the message was created) are still viewable in the archives. Whatever order the messages are seen in Papertrail is the order we received them. We see a lot of out-of-order message receipts when users are transmitting via UDP at high volumes or the sender (be it their app, a syslog daemon, etc) is doing something funky. 

I'm more than happy to answer any questions y'all have.

**Comment by josegonzalez** [comment]
@johlym that makes sense on my end. Is there a way for the user to default to using the original timestamp of the log message? If not, thats fine - its by design, so *shrug* - but just curious so I know ho to answer these questions in the future.

Thanks for the clarification!

**Comment by johlym** [comment]
Hey @josegonzalez,

Short answer is no but if they're really curious, their archived logs will have the original creation stamp as well as the receipt stamp with `second` resolution. For the vast majority of folks, the stamps will be the same.

**Comment by josegonzalez** [comment]
Gotcha, makes sense to me. UDP is UDP, can't do much about it.

**Comment by edpichler** [comment]
So @josegonzalez the problem is because UDP?

I just configured my app to use  the **Logback framework**, directly, without this `giderlab/logspout`, and **Papertrail** is showing correctly. 

![all_systems_ _papertrail](https://cloud.githubusercontent.com/assets/358696/15693341/ee3ac27c-276a-11e6-8cf3-642894d09628.png)

I conclude that the `giderlab/logspout` docker image has a limitation (or a bug), so my issue should be considered, no? This is a blocker issue, unfortunately I can't continue to use this image, I will migrate.

Thank you @johlym for your support.

**Comment by johlym** [comment]
@edpichler What was the transmission medium? UDP? TCP?

**Comment by edpichler** [comment]
@johlym I don't know. May @josegonzalez can answer.

**Comment by josegonzalez** [comment]
The example that ships to papertrail uses the Syslog adapter, which sends UDP messages.

**Comment by edpichler** [comment]
@josegonzalez my issue will not be considered as a limitation to be added on roadmap?

**Comment by josegonzalez** [comment]
@edpichler The only "fix" here is for you to use a different adapter. The logback framework ships via TCP I believe, hence why you don't have the same "bug". It's a limitation of the protocol, not of logspout, and I don't think I can fix that.

**Comment by mattaitchison** [comment]
Wouldn't this be as simple as using `syslog+tcp://` instead of `syslog://`?

**Comment by josegonzalez** [comment]
Yeah that's what I'm getting at.

**Comment by edpichler** [comment]
@mattaitchison I changed it like your example and logs stop working. Nothing is being send to papertrail.

**Comment by mattaitchison** [comment]
@edpichler Do you have tcp enabled in papertrail?

**Comment by edpichler** [comment]
@mattaitchison yes. It's working with you?

**Comment by ivanovv** [comment]
For anyone curious about that discussion @josegonzalez mentioned, it is avail here http://web.archive.org/web/20161103225502/http://help.papertrailapp.com/discussions/problems/2473-strict-log-line-ordering-heroku-drain.html
