### ISSUE TITLE
Include containers by label feature?

### ISSUE THREAD

**Issue by Ryuzavi** [gliderlabs/logspout#208]
Hey

I was just wondering if there was the opposite of the Exclude by label feature https://github.com/gliderlabs/logspout/issues/159?  

So this would be where you add a label to containers to be included in the logspout collection.  Any container missing this label would be ignored by default?

Anything like this?

Cheers,
R.

**Comment by josegonzalez** [comment]
Nope. You can make a pull request to add it though and I'll review it.

Cheers.
