### ISSUE TITLE
Module for shipping to LogDNA's REST API

### ISSUE THREAD

**Issue by dewey** [gliderlabs/logspout#211]
This is a feature request for adding an adapter for the [LogDNA](https://logdna.com/) REST API so it can be used with Docker.

Here's there API documentation: https://docs.logdna.com/docs/logdna-cli

Basically the docker log line just needs to be posted to the `/logs/ingest` endpoint with the following content:

```
{  
   "lines":[  
      {  
         "timestamp":1464041337000,
         "line":"This is an awesome log statement",
         "file":"example.log"
      }
   ]
}
```

I'll try to give it a shot myself but I don't have that much time to spend on it. If anyone wants to give it a shot that'd be great 💯

**Comment by josegonzalez** [comment]
You can create a third party module for this feature. I don't think it belongs in logspout core.

**Comment by henridf** [comment]
@dewey can't you use logdna's syslog support (https://docs.logdna.com/docs/rsyslog) ?

**Comment by dewey** [comment]
@henridf Yea, they added that now so it's not necessary any more.
