### ISSUE TITLE
The example for building a custom image isn't working

### ISSUE THREAD

**Issue by patresi** [gliderlabs/logspout#212]
Hello!

Copying the contents of https://github.com/gliderlabs/logspout/tree/master/custom and trying to build a custom image I get the following error:

```
$ docker build  .
Sending build context to Docker daemon 3.072 kB
Step 1 : FROM gliderlabs/logspout:master
# Executing 3 build triggers...
Step 1 : COPY ./build.sh /src/build.sh
lstat build.sh: no such file or directory
```

**Comment by chosenken** [comment]
Looks like the addition of `ONBUILD COPY ./build.sh /src/build.sh ` in the `Dockerfile` is causing the custom image build to fail.  A quick fix is to copy the `build.sh` file from the root folder to where your `modules.go` file is.  It will then work.

**Comment by qrpike** [comment]
Any updates on this? Stuck until this is fixed :/ 

Thanks,

**Comment by jmreicha** [comment]
I just ran into this as well.  As a workaround, I got it working by copying the `build.sh` file into my local directory with the Dockerfile as @chosenken suggested.

**Comment by josegonzalez** [comment]
Does someone want to update the custom image docs to make this explicit? Thanks.

**Comment by jmreicha** [comment]
I can probably do it but I need to solve my gcc issue first.

**Comment by jmreicha** [comment]
@josegonzalez https://github.com/gliderlabs/logspout/pull/228
