### ISSUE TITLE
Don't copy uneeded files

### ISSUE THREAD

**Issue by amouat** [gliderlabs/logspout#214]
At the moment the Dockerfile copies itself into the image before building. This means that any change to the Dockerfile breaks the cache and causes a full rebuild. It would be much faster if this file wasn't copied or was copied in later to avoid this.

**Comment by josegonzalez** [comment]
Mind filing a pr for this?

**Comment by michaelshobbs** [comment]
Not sure what the most maintainable solution should be here. Closing for now. Feel free to PR something up.
