### ISSUE TITLE
Routes via environment variables

### ISSUE THREAD

**Issue by davidnortonjr** [gliderlabs/logspout#217]
It would be a nice feature if routes (with filters, etc.) could be specified via environment variables or command, rather than requiring the mounted drive, or API calls. This would make it much easier to launch inside of Rancher.

**Comment by josegonzalez** [comment]
Would you be willing to contribute this in a pull request?

**Comment by davidnortonjr** [comment]
Yes, it might take me a while. is there a target release date for 3.2?

**Comment by josegonzalez** [comment]
Whenever I get around to making a release/someone bribes me to make a release.

**Comment by davidnortonjr** [comment]
Looking at the code, it looks like you already [can specify routes with an environment variable](https://github.com/gliderlabs/logspout/blob/master/router/routes.go#L188-L201), via the ROUTE_URIS env var, and you [can use all of the filter criteria](https://github.com/gliderlabs/logspout/blob/master/router/routes.go#L94-L106):

```docker run --rm --name="logspout"     --volume=/var/run/docker.sock:/var/run/docker.sock -e "ROUTE_URIS=raw://192.168.0.115:5000?filter.name=mysql,raw://192.168.0.115:5001?filter.name=postgres" gliderlabs/logspout:v3.1```

I will open a PR to document that more clearly.

**Comment by josegonzalez** [comment]
Sweet! Closing this!
