### ISSUE TITLE
Logging Docker Cloud's automated builds

### ISSUE THREAD

**Issue by Dids** [gliderlabs/logspout#219]
Any idea why logspout would be logging automated builds from Docker Cloud? I'm logging most of my container output to Papertrail using logspout, and I just started using Docker Cloud's automated builds (using Github webhooks), but for some reason the entire build & push output is also sent to Papertrail, and adding LOGSPOUT=ignore to the build env vars didn't do anything.

**Comment by josegonzalez** [comment]
They probably don't clear image logs or something when they store the images. We simply retrieve the logs using the docker events api, so if they are there, we will use them.

**Comment by Dids** [comment]
Thanks for clearing that up. I'm assuming there's no way to block/ignore them on my side?

**Comment by Dids** [comment]
So it turns out that `LOGSPOUT=ignore` does indeed work just fine.
The fact that Docker's combined their hub with the cloud service caused some confusion on my end, and I ended up configuring builds for the wrong repository.
