### ISSUE TITLE
routesapi just hanging

### ISSUE THREAD

**Issue by guzmo** [gliderlabs/logspout#220]
Hey,

When I'm trying to GET or POST toward /routes it just hangs and never returns an response.
I'm currently exposing port 80 after some search in the different READMES.
I've build my custom image with a modules.go as:

```
package main

import (
  _ "github.com/gliderlabs/logspout/routesapi"
  _ "github.com/looplab/logspout-logstash"
  _ "github.com/gliderlabs/logspout/transports/udp"
)
```

Anything I'm missing there?

In the log it says:

```
2016-08-05 11:03:29# logspout v3.1-custom by gliderlabs
2016-08-05 11:03:29# adapters: logstash raw udp
2016-08-05 11:03:29# options : persist:/mnt/routes
2016-08-05 11:03:29# jobs    : routes http[routes]:80 pump
2016-08-05 11:03:29# routes  :
```

Thanks in advance! :)

**Comment by guzmo** [comment]
Any suggestions? I'm currently pretty stuck

**Comment by wickman** [comment]
+1. `/logs` endpoint works fine, but can't post any routes via routes api, only via cmdline.

**Comment by wickman** [comment]
might be related to #177

**Comment by wickman** [comment]
This appears to be fixed on master, fwiw.

**Comment by guzmo** [comment]
Thanks for info :) I'm afraid I left Logspout because I got no information, then I will close this one.
