### ISSUE TITLE
Any way to write to a Host file for simple.

### ISSUE THREAD

**Issue by eromoe** [gliderlabs/logspout#226]
I only have one vps with many docker containers, I just want to gather the log into one place in Host machine. 
Document not cover this.

**Comment by ebr** [comment]
You could probably configure your local syslog daemon to accept connections from localhost, and then run logspout with `--network=host`, sending logs to `<ip-of-your-docker-bridge>:514`. this way all of your logs will end up in host's syslog (or a separate file, if you configure your syslog daemon in that way)

**Comment by eromoe** [comment]
Yes, that way is fine.
