### ISSUE TITLE
logspout doesn't take over the control of log 

### ISSUE THREAD

**Issue by eromoe** [gliderlabs/logspout#227]
docker still log into `/var/lib/docker/containers/1ec9c90e933b47d197bc57aa1f71ebd605e7c84291b6eda20f1e2ed1533ec622/1ec9c90e933b47d197bc57aa1f71ebd605e7c84291b6eda20f1e2ed1533ec622-json.log`

I have to clear those log myself.
How to only let logspout take the log?

**Comment by suchisubhra** [comment]
i have the same question.. can somebody please clarify...

**Comment by ebr** [comment]
logspout reads those logs and forwards them to wherever. it's still your responsibility to manage log rotation. I suggest looking at `DOCKER_OPTS`: `max-size` and `max-file`. https://docs.docker.com/engine/admin/logging/overview/#/json-file-options
