### ISSUE TITLE
Can misconfiguration of Loggly TLS show the connectivity issue?

### ISSUE THREAD

**Issue by c-knowles** [gliderlabs/logspout#229]
We've been using the TLS config to send our logs over to Loggly (we've also added the loggly CA cert chain into our container). The configuration that works looks like this:

```
syslog+tls://logs-01.loggly.com:6514
```

However, at first we misconfigured with this:

```
syslog+tcp://logs-01.loggly.com:6514
```

This logs the normal startup success:

```
# logspout v3.1-custom by gliderlabs
# adapters: raw syslog tcp udp tls logstash
# options : persist:/mnt/routes
# jobs    : http[routes,logs]:80 pump routes
# routes  :
#   ADAPTER ADDRESS         CONTAINERS  SOURCES OPTIONS
#   syslog+tcp  logs-01.loggly.com:6514             map[]
```

However, logs never make it through for obvious reasons. A local connection succeeds as below so not sure there will be a way to avoid/log/error in this situation but thought I'd check if you have any ideas?

```
➜ telnet logs-01.loggly.com 6514
Trying 52.34.108.226...
Connected to logs-01.loggly.com.
```

**Comment by michaelshobbs** [comment]
Not sure what makes sense here since the underlying connection seemed to succeed. If anyone else has other thoughts, please chime in. Closing for now.
