### ISSUE TITLE
Duplicate Logs After Docker Image Restart

### ISSUE THREAD

**Issue by mbrooks** [gliderlabs/logspout#234]
When a container is running and is restarted, all of the stdout for the docker container that is being restarted is sent back through logspout and logged again. 

Has anyone else seen this behavior? Let me know if I need to collect any debugging, or give any detail towards the issue. I could possibly also create a patch if pointed in the right direction.

**Comment by kamrar** [comment]
Same problem here with logspout v3.2-dev.

**Comment by iravench** [comment]
Observed the same behaviour here

**Comment by ebr** [comment]
@mbrooks, see #187 as well as a connected PR #201, which provides a fix. unfortunately, i do not know if it will ever be merged.

**Comment by erikverheij** [comment]
Same problem here. As a workaround we use the `--force-recreate` option with `docker-compose`. On container recreation the logs are cleared. Unfortunately this will not work on automatic restarts.

There is also a [feature request in docker-compose](https://github.com/docker/compose/issues/1083) to clear container logs.

**Comment by michaelshobbs** [comment]
Closing as this is covered in a couple PRs
