### ISSUE TITLE
Logspout Buffering

### ISSUE THREAD

**Issue by drakhir** [gliderlabs/logspout#245]
Does Logspout have a mechanism to provide buffering in case of network connectivity issues between host and external logging endpoint?  If so, how is it configured?  What is the default buffer size and/or how would that be set?

I don't see any mention of this type of buffer, but I was hoping it exists.  If it doesn't is this feature planned or is there another method one could use in order to prevent missing logs?

**Comment by michaelshobbs** [comment]
There is currently no buffering in regards to sending log events. PRs are welcomed however.
