### ISSUE TITLE
Docker Swarm and hostnames

### ISSUE THREAD

**Issue by taiidani** [gliderlabs/logspout#250]
I am looking into using Logspout for my Docker Swarm over the current Docker syslog driver, but I'm having a tough time getting the node's hostname to propagate to Papertrail. By default it keeps sending the Id of the Logspout container running on that node.

https://github.com/gliderlabs/logspout/issues/181 has a similar problem but solves it by adding `$(hostname)` to the SYSLOG_HOSTNAME environment variable -- in a Swarm this won't fly since the service will propagate to other nodes with the hostname set to the original host you ran the command on.

Any ideas on how I can get Logspout to work using [Papertrail's example string](http://help.papertrailapp.com/kb/configuration/configuring-centralized-logging-from-docker/#example-logspout-with-docker-swarm) while ensuring that each replicated container uses the hostname of the host it's running on?

**Comment by dnorth98** [comment]
Take a look at my fork of logspout which we use on AWS ECS (basically AWS Swarm).  I wanted to include the instance ID in the name for sending to Papertrail which is very very similar to your need here.

https://github.com/Signiant/logspout-ecs

Specifically look at the small mod to ecs-entry.sh which grabs the instanceID and then sets the hostname accordingly.  You could probably follow the same pattern here...

**Comment by taiidani** [comment]
I'm going to mark this as resolved -- we decided to go with setting SYSLOG_HOSTNAME to a generic "whole-cluster" name, so all services get wrapped up under that tag regardless of the node they run on.

Node-specific logging like its syslog output is gathered through a second Papertrail configuration on the host OS. This makes the node logging (which DevOps wants) log to entirely different Papertrail systems than services (which Engineering wants). The split actually works pretty well.
