### ISSUE TITLE
Specify Index Name When Sending to Logstash

### ISSUE THREAD

**Issue by cuthbeorht** [gliderlabs/logspout#254]
Hi All!

I am a bit noobish to the world of ELK and Logging, so please forgive any dumb questions.

Currently, I have an ELK stack setup to receive UDP packets from multiple Docker images containing Python Flask applications.  These Python applications configure a logging Filter with an application name:

```
class ServiceApiLogFilter(logging.Filter):


    def filter(self, record):

        record.application = "service-api"
        record.timestamp = str(datetime.datetime.now())

        return True
```

When Flask logs to Logstash, I pass the record.applcation.  The corresponding logstash.conf file has this entry in the output:

```
elasticsearch {
       hosts => "localhost:9200"
       index => "%{application}-%{+yyyy-MM-dd}"
}
```

Once an entry is sent, Elasticsearch creates an index with that record.application.  Is there a way to do something similar with Logspout? Or maybe pass an index name?

Thanks!

**Comment by wangyanbn** [comment]
You can try this:
Use [logspout-logstash](https://github.com/looplab/logspout-logstash) ,  add `-e LOGSTASH_FIELDS="application=service-api"` when running you app container.

**Comment by michaelshobbs** [comment]
@cuthbeorht did that work for you?

**Comment by michaelshobbs** [comment]
As we don't ship logstash in this repo and it looks like a solution is provided, I'll close this. Please feel free to comment if there's more to discuss.

**Comment by cuthbeorht** [comment]
@wangyanbn Yes! It did.  Thank you.

@michaelshobbs You can close.  Sorry for the delay.
