### ISSUE TITLE
RFE: Ability to attach additional metadata to logs based on environment/label

### ISSUE THREAD

**Issue by rocketraman** [gliderlabs/logspout#259]
I'd like to be able to use an environment variable or label to attach additional meta-data to the logs emitted by logspout. The use case for this is to tag a log message with some type of additional data that can be used downstream for handling the logs.

For example, I could tag containers that output apache-style access logging (apache httpd, nginx, etc.) with a value like "access_log" and then a downstream instance of logstash or similar tool can use that information to parse the logs into structured data.

**Comment by wangyanbn** [comment]
[logspout-logstash ](https://github.com/looplab/logspout-logstash ) can add log tags

**Comment by rocketraman** [comment]
> logspout-logstash can add log tags

This is exactly the kind of thing I was looking for. Why not make this capability available on logspout itself so that it can be used in setups that don't involve logstash? I use logspout-kafka instead of logspout-logstash.

**Comment by rocketraman** [comment]
Ah I see, I guess for logspout-kafka I can use `.Container.Config.Labels` to do something similar. I'll give that a try and if it works, I'll close this.

**Comment by rocketraman** [comment]
Using `.Container.Config.Labels` works fine. Closing.
