### ISSUE TITLE
Latest cleanhttp.go commit has broken build

### ISSUE THREAD

**Issue by kirkbgh** [gliderlabs/logspout#262]
See https://github.com/hashicorp/go-cleanhttp/commit/a45970658e51fea2c41445ff0f7e07106d007617:

When building master:

`docker build .`

Fails with:

```
# github.com/hashicorp/go-cleanhttp
../../hashicorp/go-cleanhttp/cleanhttp.go:29: unknown http.Transport field 'DialContext' in struct literal
../../hashicorp/go-cleanhttp/cleanhttp.go:30: unknown http.Transport field 'MaxIdleConns' in struct literal
../../hashicorp/go-cleanhttp/cleanhttp.go:31: unknown http.Transport field 'IdleConnTimeout' in struct literal
The command '/bin/sh -c cd /src && ./build.sh "$(cat VERSION)"' returned a non-zero code: 2

```
It seems as though the latest commit has introduced 1.7+ dependencies which are not backwards compatible with 1.6, the latest supported package in alpine 3.4.

**Comment by kirkbgh** [comment]
FWIW, I just tried using alpine:3.5, with go 1.7.3 and while it builds, launching logspout ends up giving me an error:

# logspout v3.2-dev by gliderlabs
# adapters: syslog tcp udp tls raw
# options : debug:true persist:/mnt/routes
# jobs    : http[routes,logs]:80 pump routes
# routes  : none
2017/02/12 18:22:35 pump.Run(): using inactivity timeout:  0s
2017/02/12 18:22:45 pump ended: Get http://unix.sock/containers/json?: dial tcp: lookup unix.sock on 127.0.0.11:53: read udp 127.0.0.1:42810->127.0.0.11:53: i/o timeout

**Comment by mccricardo** [comment]
Having the same issue.

**Comment by amitripshtos** [comment]
same, I really love this project but it breaks my CI constantly when I'm building this image :(

**Comment by richard-mauri** [comment]
I have a project that depends on hashicorp vault that is now broken.
I am building with go 1.7.4
Are we both victims of a bad hashi commit; how can we defend ourselves?

> vagrant@vaultaccess-host:~/vaultaccess$ go version
> go version go1.7.4 linux/amd64
> vagrant@vaultaccess-host:~/vaultaccess$ 
> vagrant@vaultaccess-host:~/vaultaccess$ ./build.sh 
> # github.com/hashicorp/vault/vendor/github.com/hashicorp/go-cleanhttp
> ../github.com/hashicorp/vault/vendor/github.com/hashicorp/go-cleanhttp/cleanhttp.go:29: unknown http.Transport field 'DialContext' in struct literal
> ../github.com/hashicorp/vault/vendor/github.com/hashicorp/go-cleanhttp/cleanhttp.go:30: unknown http.Transport field 'MaxIdleConns' in struct literal
> ../github.com/hashicorp/vault/vendor/github.com/hashicorp/go-cleanhttp/cleanhttp.go:31: unknown http.Transport field 'IdleConnTimeout' in struct literal

**Comment by rosteroster** [comment]
make sure you're using a supported version of Go. Can confirm that I was getting this error in Go 1.6 and fixed in Go 1.7

**Comment by michaelshobbs** [comment]
@kirkbgh @richard-mauri @amitripshtos @mccricardo We now test builds on every merge and I **think** this is ok now. Can someone confirm this is fixed out in the wild?

**Comment by mccricardo** [comment]
@michaelshobbs I was able to build it successfully.

**Comment by smartb-ansible** [comment]
We are seeing this exact error on Go 1.8, building the Circonus Protocol Observer:
```
# github.com/hashicorp/go-cleanhttp
    tmp/protocol_observer/src/github.com/hashicorp/go-cleanhttp/cleanhttp.go:30: unknown http.Transport field 'DialContext' in struct literal
    tmp/protocol_observer/src/github.com/hashicorp/go-cleanhttp/cleanhttp.go:31: unknown http.Transport field 'MaxIdleConns' in struct literal
    tmp/protocol_observer/src/github.com/hashicorp/go-cleanhttp/cleanhttp.go:32: unknown http.Transport field 'IdleConnTimeout' in struct literal
    # github.com/hashicorp/go-cleanhttp
    ../../../hashicorp/go-cleanhttp/cleanhttp.go:30: unknown http.Transport field 'DialContext' in struct literal
    ../../../hashicorp/go-cleanhttp/cleanhttp.go:31: unknown http.Transport field 'MaxIdleConns' in struct literal
    ../../../hashicorp/go-cleanhttp/cleanhttp.go:32: unknown http.Transport field 'IdleConnTimeout' in struct literal
```
