### ISSUE TITLE
unrecognized import path "context" 

### ISSUE THREAD

**Issue by yamingwa** [gliderlabs/logspout#267]
I got the following error when building logspout on docke hub:
`Building in Docker Cloud's infrastructure...
Cloning into '.'...

KernelVersion: 4.4.0-59-generic
Os: linux
BuildTime: 2017-01-10T23:09:49.630531934+00:00
ApiVersion: 1.24
Version: 1.12.6-cs6
GitCommit: 712e864
Arch: amd64
GoVersion: go1.6.4
Starting build of index.docker.io/yamingwa/logspout:1.0...
Step 1 : FROM gliderlabs/alpine:latest

 ---> 9cfff538e583

Step 2 : ENTRYPOINT /bin/logspout

 ---> Running in abea7d34e6b1

 ---> 95e3d77f945e

Removing intermediate container abea7d34e6b1

Step 3 : VOLUME /mnt/routes

 ---> Running in 7af33bb87396

 ---> be6fcfcd9441

Removing intermediate container 7af33bb87396

Step 4 : EXPOSE 80

 ---> Running in 8811aa7af66a

 ---> 7f6a8df7404c

Removing intermediate container 8811aa7af66a

Step 5 : COPY . /src

 ---> a103760c3e84

Removing intermediate container c6354e98a74c

Step 6 : RUN cd /src && ./build.sh "$(cat VERSION)"

 ---> Running in 513ad0bb9bf2

fetch http://alpine.gliderlabs.com/alpine/v3.4/main/x86_64/APKINDEX.tar.gz

fetch http://alpine.gliderlabs.com/alpine/v3.4/community/x86_64/APKINDEX.tar.gz

(1/36) Installing binutils-libs (2.26-r0)

(2/36) Installing binutils (2.26-r0)

(3/36) Installing gmp (6.1.0-r0)

(4/36) Installing isl (0.14.1-r0)

(5/36) Installing libgomp (5.3.0-r0)

(6/36) Installing libatomic (5.3.0-r0)

(7/36) Installing libgcc (5.3.0-r0)

(8/36) Installing pkgconf (0.9.12-r0)

(9/36) Installing pkgconfig (0.25-r1)

(10/36) Installing mpfr3 (3.1.2-r0)

(11/36) Installing mpc1 (1.0.3-r0)

(12/36) Installing libstdc++ (5.3.0-r0)

(13/36) Installing gcc (5.3.0-r0)

(14/36) Installing make (4.1-r1)

(15/36) Installing musl-dev (1.1.14-r14)

(16/36) Installing libc-dev (0.7-r0)

(17/36) Installing fortify-headers (0.8-r0)

(18/36) Installing g++ (5.3.0-r0)

(19/36) Installing build-base (0.4-r1)

(20/36) Installing ca-certificates (20161130-r0)

(21/36) Installing libssh2 (1.7.0-r0)

(22/36) Installing libcurl (7.52.1-r1)

(23/36) Installing expat (2.2.0-r0)

(24/36) Installing pcre (8.38-r1)

(25/36) Installing git (2.8.3-r0)

(26/36) Installing go (1.6.3-r0)

(27/36) Installing libbz2 (1.0.6-r5)

(28/36) Installing libffi (3.2.1-r2)

(29/36) Installing gdbm (1.11-r1)

(30/36) Installing ncurses-terminfo-base (6.0-r7)

(31/36) Installing ncurses-terminfo (6.0-r7)

(32/36) Installing ncurses-libs (6.0-r7)

(33/36) Installing readline (6.3.008-r4)

(34/36) Installing sqlite-libs (3.13.0-r0)

(35/36) Installing python (2.7.12-r0)

(36/36) Installing mercurial (3.8.2-r0)

Executing busybox-1.24.2-r12.trigger

Executing ca-certificates-20161130-r0.trigger

OK: 414 MiB in 47 packages

[91mpackage context: unrecognized import path "context" (import path does not begin with hostname)
[0m
Removing intermediate container 513ad0bb9bf2

The command '/bin/sh -c cd /src && ./build.sh "$(cat VERSION)"' returned a non-zero code: 1`

I guess this is about the version of go. It turns out go 1.7 will import context but here we are using go 1.6.3 for gliderlabs/alpine:latest.

**Comment by nguyendung17** [comment]
Have you resolved that issue?
