### ISSUE TITLE
any plan to support docker service logs? 

### ISSUE THREAD

**Issue by slawekgh** [gliderlabs/logspout#271]
in new docker 1.13.x there is new CLI for swarm mode - "docker service logs"
after several tests seems than logspout can read only logs from containers running on the same machine

no support for remote containers in swarm service 

any future plan to improve this ?

**Comment by slawekgh** [comment]
+1

**Comment by josegonzalez** [comment]
No. It only reads logs from the local machine. You'll need to run logspout on every system in your swarm cluster.

**Comment by slawekgh** [comment]
thx
