### ISSUE TITLE
logstash: could not write:write udp ... write: connection refused

### ISSUE THREAD

**Issue by oxfordatec** [gliderlabs/logspout#272]
Hi dudes, 

We are unable to send logs to an external Logstash server from rancher containers.
The error we are getting is:

28/02/2017 11:12:29#   ADAPTER	ADDRESS		CONTAINERS	SOURCES	OPTIONS
28/02/2017 11:12:29#   logstash	esk02.th:5044				map[]
28/02/2017 11:12:292017/02/28 11:12:29 logstash: could not write:write udp 10.42.223.102:39829->10.160.7.58:5044: write: connection refused

The external Logstash server getting logs from other servers as well other than Rancher.
The Logstash server conf:

input {
  beats {
    port => 5044
    ssl => true
    ssl_certificate => "file.crt" 
    ssl_key => "file.key" 
  }
  udp {
    port  => 5044
    codec => json
  }
  tcp {
    port  => 5044
    codec => json
  }
}

Anyone got any clue why cant connect to Logstash?

**Comment by digitalkaoz** [comment]
same here...

**Comment by digitalkaoz** [comment]
@oxfordatec `v2` is working fine, but i feel very uncomfortable with that

**Comment by digitalkaoz** [comment]
may @josegonzalez has an idea?

**Comment by teamon** [comment]
I'm using `logspout v3.2-dev-custom` with rancher 1.4.1 and it's all fine. 
The image I'm using is just single line `FROM gliderlabs/logspout:master` with customized modules.go.
I only get the above error message during logstash restart (which seems reasonable).

**Comment by digitalkaoz** [comment]
@teamon yes you are correct, restarting the container once logstash is completely up makes the error go away

**Comment by michaelshobbs** [comment]
@oxfordatec can you confirm this is still an issue with `logspout:master`?

**Comment by oxfordatec** [comment]
@michaelshobbs it is working fine for us. Turned out to be a misconfiguration issue on Logstash.

**Comment by Panda-Ann** [comment]
@oxfordatec Hi,i met the same error,can you show your Logstash configfile? thx

**Comment by oxfordatec** [comment]
@Panda-Ann 
```
input {

  tcp {
    port => 5044
    type => syslog
  }

  udp {
    port => 5044
    codec => json
    type => dockerlog
  }

}

filter {

}


output {

  elasticsearch {
    hosts => ["some_ip:some_port"]
    codec => "json"
  } 
  
}
``` 
Make sure that Logstash is listening on its port and you would be fine.

**Comment by Panda-Ann** [comment]
@oxfordatec thx
