### ISSUE TITLE
Trying to figure out why logspout does not collect logs generated by a container which is started with "-t"

### ISSUE THREAD

**Issue by yamingwa** [gliderlabs/logspout#275]
I've read logspout source code and I find the following logic:
`if container.Config.Tty {	
    debug("pump.pumpLogs():", id, "ignored: tty enabled")
    return
}`
If logpout is using docker api like 'docker logs <container_id>', I think we can get the logs even containers are started with tty. So is this logic trying to avoid some other effect of the tty configuration or something?

**Comment by michaelshobbs** [comment]
We're trying to avoid sending logs for "non-service" or "testing" containers; for lack of a better phrase. For example we don't want to log events from something like this (contrived as it might be):

```
$ docker run --rm -ti ubuntu:trusty bash
root@52b3c03d477f:/# find /var/lib/apt/
/var/lib/apt/
/var/lib/apt/lists
/var/lib/apt/keyrings
/var/lib/apt/keyrings/ubuntu-archive-keyring.gpg
/var/lib/apt/periodic
/var/lib/apt/extended_states
/var/lib/apt/mirrors
/var/lib/apt/mirrors/partial
root@52b3c03d477f:/# rm -rf /var/lib/apt
root@52b3c03d477f:/# exit
exit
```

For logspout questions and discussion, please visit our `#logspout` on https://glider-slackin.herokuapp.com/
