### ISSUE TITLE
logspout stops sending logs via tcp

### ISSUE THREAD

**Issue by akosyrev** [gliderlabs/logspout#277]
After 10-20mins after start container does not send any packets.

My problem was sending containers logs to logstash.
1.  I did changes to modules.go as described [here ](https://github.com/looplab/logspout-logstash/blob/master/README.md
)
2. Compile logspout on my host: `GOOS=linux GOARCH=amd64 CGO_ENABLED=0 go build` 
```
go version
go version go1.7.4 linux/amd64
```
3. Add binary to /bin

After start container sends logs well, no drops or anything wrong. But after sometime it stops sending packets, I see it in CPU and network usage. My main container (which generates logs to stdout) works, its responses for requests, writes logs..

I verified if it is logstash-module problem. I ran luisbebop/echo-serverPorts and tried raw TCP sending and faced same beavior.

Any help is appreciated

**UPD1**
Restart logspout-container fixes problem for 10-20 mins.

This is my logsout output after start:
```
30.03.2017 13:11:56# logspout  by gliderlabs
30.03.2017 13:11:56# adapters: syslog tcp udp tls logstash raw
30.03.2017 13:11:56# options : persist:/mnt/routes
30.03.2017 13:11:56# jobs    : routes http[logs,routes]:80 pump
30.03.2017 13:11:56# routes  :
30.03.2017 13:11:56#   ADAPTER	ADDRESS		CONTAINERS	SOURCES	OPTIONS
30.03.2017 13:11:56#   raw+tcp	10.6.109.62:8800*load*			map[]
```

**Comment by michaelshobbs** [comment]
What version are you running? Can you also post the logspout container logs after you stop seeing packets being sent?

**Comment by michaelshobbs** [comment]
potentially related to #268

**Comment by akosyrev** [comment]
Version: v3.2-dev

There is no other logs after packets stop being sent.
Only this lines after startup:
```
31.03.2017 9:51:42# logspout  by gliderlabs
31.03.2017 9:51:42# adapters: syslog tcp udp tls logstash raw
31.03.2017 9:51:42# options : persist:/mnt/routes
31.03.2017 9:51:42# jobs    : http[routes,logs]:80 pump routes
31.03.2017 9:51:42# routes  :
31.03.2017 9:51:42#   ADAPTER	ADDRESS		CONTAINERS	SOURCES	OPTIONS
31.03.2017 9:51:42#   raw+tcp	10.6.109.62:8800*load*			map[]
```
and at 10:02 packets lost somewhere without any additional info/logs or errors.

**Comment by akosyrev** [comment]
If I use UDP, problem does not appears. Logs are transmitted for 3 days. Some lines are dropped (UDP "feature") but logspout continues sending logs and I see ~99% of them in my ElasticSearch.

Maybe this info could be helpful

**Comment by michaelshobbs** [comment]
Potential fix + tests were merged in f18e503780b8f3abb3771ffaa97e5d2971199f9b

**Comment by akosyrev** [comment]
Sorry for my late answer. 
Recompiled with logspout v3.3-dev, master-branch. The bug still exists.

The commit https://github.com/gliderlabs/logspout/commit/f18e503780b8f3abb3771ffaa97e5d2971199f9b  contains some changes and tests about syslog adapter. And this bug is about TCP connection, I think.

**Comment by michaelshobbs** [comment]
Apologies as I assumed you were using tcp+syslog. It would seem yore using the logstash adapter. The adapters are actually the responsible code paths for connecting and reconnecting to the configured logging service. 

As we are no longer seeing this issue with the syslog adapter, I'm thinking your issue probably lies with the logstash adapter. Please let us know if you have additional information or even a PR that pertaining to the tcp transport.

**Comment by renjithwarrier94** [comment]
I am facing the same issue. The version I am using is v3.2.2. I used the httpstream module and found that logspout is actually reading the logs from stdout. The following the log for logspout and the las few lines indicate what happens after the logs are stopped being sent.


`clogspout.0.q8qrts7rn4pr@Landscape-5-1508835773TFAS-MZ-APP-10.37.4.213    | # logspout v3.2.2 by gliderlabs
logspout.0.sensae9262gu@Landscape-5-1508835773TFAS-MZ-APP-10.37.4.213    | # logspout v3.2.2 by gliderlabs
logspout.0.q8qrts7rn4pr@Landscape-5-1508835773TFAS-MZ-APP-10.37.4.213    | # adapters: syslog tcp udp tls raw
logspout.0.sensae9262gu@Landscape-5-1508835773TFAS-MZ-APP-10.37.4.213    | # adapters: syslog tcp udp tls raw
logspout.0.q8qrts7rn4pr@Landscape-5-1508835773TFAS-MZ-APP-10.37.4.213    | # options : persist:/mnt/routes
logspout.0.sensae9262gu@Landscape-5-1508835773TFAS-MZ-APP-10.37.4.213    | # options : persist:/mnt/routes
logspout.0.xx0qax9a486k@Landscape-5-1508835773TFAS-MZ-APP-10.37.4.207    | # logspout v3.2.2 by gliderlabs
logspout.0.q8qrts7rn4pr@Landscape-5-1508835773TFAS-MZ-APP-10.37.4.213    | # jobs    : http[logs,routes]:80 pump routes
logspout.0.iqbarwp8bpip@Landscape-5-1508835773TFAS-MZ-APP-10.37.4.207    | # logspout v3.2.2 by gliderlabs
logspout.0.xx0qax9a486k@Landscape-5-1508835773TFAS-MZ-APP-10.37.4.207    | # adapters: raw syslog tcp udp tls
logspout.0.iqbarwp8bpip@Landscape-5-1508835773TFAS-MZ-APP-10.37.4.207    | # adapters: udp tls raw syslog tcp
logspout.0.xx0qax9a486k@Landscape-5-1508835773TFAS-MZ-APP-10.37.4.207    | # options : persist:/mnt/routes
logspout.0.iqbarwp8bpip@Landscape-5-1508835773TFAS-MZ-APP-10.37.4.207    | # options : persist:/mnt/routes
logspout.0.iqbarwp8bpip@Landscape-5-1508835773TFAS-MZ-APP-10.37.4.207    | # jobs    : http[logs,routes]:80 pump routes
logspout.0.xx0qax9a486k@Landscape-5-1508835773TFAS-MZ-APP-10.37.4.207    | # jobs    : http[logs,routes]:80 pump routes
logspout.0.iqbarwp8bpip@Landscape-5-1508835773TFAS-MZ-APP-10.37.4.207    | # routes  :
logspout.0.iqbarwp8bpip@Landscape-5-1508835773TFAS-MZ-APP-10.37.4.207    | #   ADAPTER	ADDRESS		CONTAINERS	SOURCES	OPTIONS
logspout.0.xx0qax9a486k@Landscape-5-1508835773TFAS-MZ-APP-10.37.4.207    | # routes  :
logspout.0.iqbarwp8bpip@Landscape-5-1508835773TFAS-MZ-APP-10.37.4.207    | #   raw+tcp	logstash:5545				map[]
logspout.0.xx0qax9a486k@Landscape-5-1508835773TFAS-MZ-APP-10.37.4.207    | #   ADAPTER	ADDRESS		CONTAINERS	SOURCES	OPTIONS
logspout.0.xx0qax9a486k@Landscape-5-1508835773TFAS-MZ-APP-10.37.4.207    | #   raw+tcp	logstash:5545				map[]
logspout.0.xx0qax9a486k@Landscape-5-1508835773TFAS-MZ-APP-10.37.4.207    | 2017/10/26 13:54:16 raw: write tcp 10.0.9.15:57614->10.0.9.6:5545: write: no route to host
logspout.0.sensae9262gu@Landscape-5-1508835773TFAS-MZ-APP-10.37.4.213    | # jobs    : pump routes http[logs,routes]:80
logspout.0.q8qrts7rn4pr@Landscape-5-1508835773TFAS-MZ-APP-10.37.4.213    | # routes  :
logspout.0.sensae9262gu@Landscape-5-1508835773TFAS-MZ-APP-10.37.4.213    | # routes  :
logspout.0.q8qrts7rn4pr@Landscape-5-1508835773TFAS-MZ-APP-10.37.4.213    | #   ADAPTER	ADDRESS		CONTAINERS	SOURCES	OPTIONS
logspout.0.sensae9262gu@Landscape-5-1508835773TFAS-MZ-APP-10.37.4.213    | #   ADAPTER	ADDRESS		CONTAINERS	SOURCES	OPTIONS
logspout.0.q8qrts7rn4pr@Landscape-5-1508835773TFAS-MZ-APP-10.37.4.213    | #   raw+tcp	logstash:5545				map[]
logspout.0.sensae9262gu@Landscape-5-1508835773TFAS-MZ-APP-10.37.4.213    | #   raw+tcp	logstash:5545				map[]
logspout.0.sensae9262gu@Landscape-5-1508835773TFAS-MZ-APP-10.37.4.213    | 2017/10/26 13:29:07 raw: write tcp 10.0.9.14:38782->10.0.9.6:5545: write: no route to host
logspout.0.xx0qax9a486k@Landscape-5-1508835773TFAS-MZ-APP-10.37.4.207    | 2017/10/26 13:54:16 routes ended: %!s(<nil>)
logspout.0.sensae9262gu@Landscape-5-1508835773TFAS-MZ-APP-10.37.4.213    | 2017/10/26 13:29:07 routes ended: %!s(<nil>)`
