### ISSUE TITLE
docker hub :latest tag is out of date

### ISSUE THREAD

**Issue by nhaugo** [gliderlabs/logspout#283]
The docs reference the `latest` tag however it does not look like this has been updated in 10 months even though `master` has been. Can this be updated.

**Comment by mattaitchison** [comment]
The behavior of the `latest` tag is documented in the [README](https://github.com/gliderlabs/logspout#logspout).

> Docker Hub automated builds for gliderlabs/logspout:latest and progrium/logspout:latest are now pointing to the release branch. For master, use gliderlabs/logspout:master. Individual versions are also available as saved images in releases.
