### ISSUE TITLE
Update /custom/

### ISSUE THREAD

**Issue by luckydonald** [gliderlabs/logspout#285]
With #281 removing the `build.sh` file, it should no longer be needed in the custom folder.

**Comment by luckydonald** [comment]
While at it, maybe telling that `modules.go` is automatically included `ONBUILD` would be a nice thing, so you know you don't need to `COPY` them yourself.

**Comment by michaelshobbs** [comment]
Mind putting a PR together for this?

**Comment by luckydonald** [comment]
@michaelshobbs There also seem to be errors with pulling now, as there is no `git` support any more.
```sh
# Executing 3 build triggers...
Step 1/1 : COPY ./modules.go ${LSPATH}/modules.go
Step 1/1 : RUN cd $LSPATH && go get
 ---> Running in e0996a19873c
go: missing Git command. See https://golang.org/s/gogetcmd
package github.com/looplab/logspout-logstash: exec: "git": executable file not found in $PATH
```
This is happening with [logspout-logstash](https://github.com/looplab/logspout-logstash/tree/e00429eefff88ecbaa2ed8a662463eaeb1474e81).

#### File `modules.go`
```go
package main

import (
  	_ "github.com/looplab/logspout-logstash"
	_ "github.com/gliderlabs/logspout/adapters/syslog"
	_ "github.com/gliderlabs/logspout/transports/tcp"
)
```

**Comment by michaelshobbs** [comment]
I think this is a case for keeping `build.sh` in custom, no? Try using that to build your image and let me know what happens.

**Comment by luckydonald** [comment]
I think because of the `ONBUILD` triggering and failing before I can even `ADD` a custom `build.sh` script, this isn't working.
Never really used golang before, so I am having hard times with compile errors, I guess something in `logspout-logstash` is not working right, too.

**Comment by michaelshobbs** [comment]
@luckydonald check out #289 and use the `dockerfile` and `modules.go` found in `custom/` (once master is updated of course)

**Comment by luckydonald** [comment]
Oh, this looks nice.

**Comment by luckydonald** [comment]
Would adding
```sh
chmod +x build.sh
```
to the [`ONBUILD RUN` step](https://github.com/gliderlabs/logspout/blob/67ee3831cbd0594361bb3381380c65bdbeb3c20f/Dockerfile#L11)  hurt?

**Comment by michaelshobbs** [comment]
The file is checked in executable. Thus, `chmod +x build.sh` is not necessary. Are you having a specific issue related to that file?

**Comment by luckydonald** [comment]
More an copy paste issue. I mean it is easily fixable by the user, but could add a little bit of comfort.
Other than that, it is working great. 👍
