### ISSUE TITLE
Massive docker image

### ISSUE THREAD

**Issue by mattaitchison** [gliderlabs/logspout#288]
#286 caused `logspout:master` to jump from `5mb` to `287mb`

**Comment by mattaitchison** [comment]
Im sure #281 caused this as well..

**Comment by progrium** [comment]
Gotta watch that size. Ideas to bring it back down?

**Comment by josegonzalez** [comment]
Use fewer layers?

**Comment by mattaitchison** [comment]
The main `Dockerfile` should be reverted to the old(9b4a90d) behavior and build improvements (glide, go version) should be moved into `build.sh`.

**Comment by luckydonald** [comment]
There are many `RUN` commands which could be put into one.
Instead of 
```Dockerfile
RUN command1
RUN command2
```
just do 
```Dockerfile
RUN command1 && command2 && \
    command3 
```

**Comment by michaelshobbs** [comment]
Looking at this now in fact

**Comment by mattaitchison** [comment]
@luckydonald `build.sh` is a better option since custom builds require the same behavior.

**Comment by michaelshobbs** [comment]
@mattaitchison clearly I jumped the gun here. Am I correct in thinking there is not a way to use vendored deps AND support building custom images?

**Comment by michaelshobbs** [comment]
Nvm. I sorted it out. I'll also add tests to build a custom image so we don't break that unexpectedly.

**Comment by michaelshobbs** [comment]
For the record, `v3.1` is ~15MB
```
root@desdemona:~# docker images | grep logspout
gliderlabs/logspout         v3.1                d04eef404210        10 months ago       15.27 MB
```
