### ISSUE TITLE
Latest push to docker is breaking

### ISSUE THREAD

**Issue by luberg** [gliderlabs/logspout#294]
We pulled latest from https://hub.docker.com/r/gliderlabs/logspout/builds/bzeszmaugxr6qm9stydhr3x/ on a kubernetes cluster and are getting this error message:

```
# logspout v3.2 by gliderlabs
# adapters: syslog tcp udp tls raw
# options : persist:/mnt/routes
!! x509: failed to load system roots and no roots provided

```

**Comment by michaelshobbs** [comment]
gah! ok. fixing

**Comment by michaelshobbs** [comment]
@luberg i'm assuming you're using `syslog+tls` or the like?

**Comment by michaelshobbs** [comment]
scratch that last question. i've got a PR coming with the fix and tests as well

**Comment by luberg** [comment]
Awesome!  Works great now. Thanks!
