### ISSUE TITLE
breaking change: routes api returns "null\n" instead of an empty list

### ISSUE THREAD

**Issue by pmbauer** [gliderlabs/logspout#299]
Routes API used to return the JSON literal `[]` when there were no routes.  It now returns `null\n`.
I believe this was introduced here:

https://github.com/gliderlabs/logspout/commit/cb652d411afc6938424e830f6f88c985f1cc9a6c#diff-da28fe63f6943ed23c90b01cc3b7565fL57

**Comment by michaelshobbs** [comment]
Fixed with #300.

@mattaitchison or @josegonzalez or @progrium can one of you guys get this merged? gotta head out to the airport.

**Comment by josegonzalez** [comment]
Will merge when tests pass, though I'm going to leave releasing up to you :)

**Comment by michaelshobbs** [comment]
@pmbauer give master a shot once it's all built and let me know if it's working again. Sorry for the inconvenience

**Comment by pmbauer** [comment]
np; noticed it when rolling out a new daemon; I put some logic in our playbook to work around it, but given the context of that commit, wasn't 100% on what behavior was correct.  Thanks so much for the fix!

**Comment by pmbauer** [comment]
+1K Thanks! pulled down the latest master into our build, works great.
