### ISSUE TITLE
Cannot connect to Docker endpoint

### ISSUE THREAD

**Issue by jamesfielder** [gliderlabs/logspout#304]
When running logspout with:
```
docker run -it --volume=/var/run/docker.sock:/var/run/docker.sock \
 --env DEBUG="true" gliderlabs/logspout
```
I am given the following error immediately after startup
```
2017/05/09 15:50:30 setting allowTTY to: false
2017/05/09 15:50:30 setting retryCount to: 10
# logspout v3.2.1 by gliderlabs
# adapters: tls raw syslog tcp udp
# options : debug:true persist:/mnt/routes
# jobs    : http[logs,routes]:80 pump routes
# routes  : none
2017/05/09 15:50:30 pump.Run(): using inactivity timeout:  0s
2017/05/09 15:50:30 pump ended: cannot connect to Docker endpoint
```

While I know I haven't specified an output in the command above the same thing seems to happen no matter what the output driver I select is. I am using docker 17.04-ce on Centos 7. Has anyone got any ideas what might be wrong here?

**Comment by michaelshobbs** [comment]
I don't personally use CentOS but off the top of my head I'd start by ensuring the path to the `docker.sock` file is correct and then have a look at the selinux logs to make sure you're not hitting some sort of permissions issue there.

**Comment by jamesfielder** [comment]
Thanks so much for the advice. It turned out it was user error alas: another engineer on my project had set dockerd to not bind to docker.sock, but instead 0.0.0.0:2375. For anyone who comes across this error in the future, if you check your process list for `dockerd -H ip:port` you can see if it is not bound to the normal unix socket. I wasn't even aware this was possible until I looked into this. You can make dockerd bind to both by specifying multiply `-H` flags on startup, see [here](https://docs.docker.com/engine/reference/commandline/dockerd/#daemon-socket-option).

Sorry to have wasted anyone's time, but hopefully this can be helpful for someone in the future. Logspout works wonderfully as well!

**Comment by michaelshobbs** [comment]
No worries at all. Glad you got it sorted out and thanks for the explanation.
