### ISSUE TITLE
ALLOW_TTY not working

### ISSUE THREAD

**Issue by pasifus** [gliderlabs/logspout#310]
Running logspout with logspout-logstash

```
  logspout:
    container_name: logspout
    build: logspout/
    #ports:
    #  - "8000:80"
    environment:
      ROUTE_URIS: "logstash+tcp://${LOGSTASH_HOST}:5000"
      LOGSTASH_TAGS: "logspout"
      RETRY_STARTUP: "true"
      ALLOW_TTY: "true"
      DEBUG: 1
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    restart: on-failure
```

if running :
`docker run --name=logs_generator -d chentex/random-logger:latest`

it's ok, but if add **-t** don't see input on logstash

**Comment by GiGurra** [comment]
I have the same problem. ALLOW_TTY doesn't seem to do anything

**Comment by josegonzalez** [comment]
What version of logspout are you running, and if it is a custom version, what is that based on?

**Comment by GiGurra** [comment]
docker image gliderlabs/logspout:latest

**Comment by th0th** [comment]
Any update on this? I am using `gliderlabs/logspout:latest` (pulled just minutes ago) and the issue still seems to persist.

**Comment by michaelshobbs** [comment]
If someone has time to work on this, I'm happy to help get it merged.

**Comment by michaelshobbs** [comment]
@th0th @pasifus @GiGurra can you try out the image linked in #319 and report back? I'd like to make sure it addresses your issue before merging.

**Comment by th0th** [comment]
@michaelshobbs I've tested `adopteunops/logspout:latest` and it works. Thanks a lot for the fix!
