### ISSUE TITLE
Websocket problem

### ISSUE THREAD

**Issue by marianogenovese** [gliderlabs/logspout#320]
Hi,

Im using logspout http module and a websocket client (browser) for log streaming, and the first connection made to logspout via websocket is correct, but when i refresh my browser and try to connect to logspout via websocket the connection is not made. I get this message from docker logspout container:

```
# logspout v3.2.2 by gliderlabs
# adapters: raw syslog tcp udp tls
# options : persist:/mnt/routes
# jobs    : pump routes http[logs,routes]:80
# routes  : none
panic: send on closed channel

goroutine 9 [running]:
panic(0x56160f58a380, 0xc420286630)
        /usr/lib/go/src/runtime/panic.go:500 +0x1a5
github.com/gliderlabs/logspout/router.(*containerPump).send(0xc4201b4540, 0xc4202962c0)
        /go/src/github.com/gliderlabs/logspout/router/pump.go:375 +0x153
github.com/gliderlabs/logspout/router.newContainerPump.func1(0x56160f2b7a7f, 0x6, 0x56160f75e820, 0xc420024118)
        /go/src/github.com/gliderlabs/logspout/router/pump.go:360 +0x21f
created by github.com/gliderlabs/logspout/router.newContainerPump
        /go/src/github.com/gliderlabs/logspout/router/pump.go:364 +0x19a
```

**Comment by dhicksNTIA** [comment]
@marianogenovese did you end up figuring this out?

**Comment by dhicksNTIA** [comment]
@michaelshobbs any advice you have for this would be super helpful

**Comment by dhicksNTIA** [comment]
Found the issue (for anyone who cares) in my nginx.conf:

    location /logs {
        proxy_pass http://ws-logger/logs;
        proxy_http_version 1.1;
        proxy_set_header Upgrade "websocket";
        proxy_set_header Connection "upgrade";
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto https;
        proxy_read_timeout 86400; # neccessary to avoid websocket timeout disconnect
        proxy_redirect off;
    }

**Comment by michaelshobbs** [comment]
fix provided
