### ISSUE TITLE
New release 3.3 of logspout due to problems with log backlogs

### ISSUE THREAD

**Issue by dagvl** [gliderlabs/logspout#324]
Hi,

we are currently having a lot of issues due to logspout 3.2.2 (and older) ending up requesting the entire log backlog when a container starts up. 3.3-dev has the new feature where you can set TAIL=X to avoid this. I've tested it and it solves our problem.

I'm wondering if there is plans to cut a new release with this feature soon?

**Comment by michaelshobbs** [comment]
We certainly could. I was hoping to get a few more bug fixes in before the next release. Is there something not working for you with the 3.3-dev tag?

**Comment by dagvl** [comment]
We are currently running the docker image based on b6a1988311d3f84efcd5c4281e1c36e8773b3216 in out dev env, but we have not given it extensive testing yet. It does fix the log re-parsing issue that broke things for us.

For out dev envs now I have just pushed a copy of the current master with a custom tag to our own docker repo so we don't have a dependency to an ever-changing "master" image tag. 

It would be nice to get off our custom image and back to the official builds, but a timeline of a few weeks still works for me if you have other fixes in the pipeline.

**Comment by michaelshobbs** [comment]
Understood. I'll cut 3.2.3 right now
