### ISSUE TITLE
Can I rotate log files?

### ISSUE THREAD

**Issue by zhaoyao91** [gliderlabs/logspout#327]
How does logspout collect logs from containers? We have another job which rotate and delete old logs of the raw container logs, and logspout cannot collect logs anymore.

**Comment by michaelshobbs** [comment]
logspout uses the docker API to stream logs to your configured logging endpoint. I believe there is an open bug about issues when rotating logs. As part of your log rotation, you could also restart the logspout container. That should work around the issue. 

Also, why not let the docker daemon handle log rotation. See [here](https://docs.docker.com/engine/admin/logging/json-file/#options)

**Comment by zhaoyao91** [comment]
Thanks so much! I didn't notice that docker has already provided so convenient methods.
