### ISSUE TITLE
Would need a way to specify the hostname to use when running logspout as a global service

### ISSUE THREAD

**Issue by chris7444** [gliderlabs/logspout#328]
issue #181 describes what I want to achieve with logspout
[https://github.com/gliderlabs/logspout/issues/181](url)

To summarize, here is how I want logspout to output messages

Format1:  timestamp  field2 NameOfContainer ...

where field2 is the name of the docker host running the container rather than an ID (default)

I know I can use the SYSLOG_HOSTNAME environment variable to have logspout spit messages with the name of the docker host but this does not work when defining a global service for logspout

example compose file

version: "3"
networks:
  logging:
services:
  logspout:
    image: gliderlabs/logspout:{{ logspout_version }}
    environment:
      -SYSLOG_HOSTNAME="something"
    networks:
      - logging
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command:
      syslog://{{groups.logger[0]}}.{{domain_name}}:514
    deploy:
      mode: global

The value for SYSLOG_HOSTNAME will be the same for all replicas of the logspout container and this is not what I want. 

A suggestion would be to do something similar to what is done for node-exporter . In the following compose file, I can see that the name of the host is passed to the container by mounting /etc/hostname to /etc/host_hostname. By using a similar technic it would be possible to run logspout as a global service and have each and every instance 

  node-exporter:
    image: basi/node-exporter:{{ node_exporter_version }}
    networks:
      - monitoring
    ports:
      - 9100:9100
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
      - /etc/hostname:/etc/host_hostname:ro
    environment:
      - HOST_HOSTNAME=/etc/host_hostname

more info  here: [https://hub.docker.com/r/basi/node-exporter/](url)

**Comment by chris7444** [comment]
suggested change
(please forgive me I am not using a pull request now but I am learning everything at the same time, docker, ansible, python, go, git...)

[root@svt2-ucp01 logspout]# git diff adapters/syslog/syslog.go
diff --git a/adapters/syslog/syslog.go b/adapters/syslog/syslog.go
index e44f787..3b8b27c 100644
--- a/adapters/syslog/syslog.go
+++ b/adapters/syslog/syslog.go
@@ -4,6 +4,7 @@ import (
        "bytes"
        "errors"
        "fmt"
+       "io/ioutil"
        "log"
        "log/syslog"
        "net"
@@ -67,8 +68,14 @@ func NewSyslogAdapter(route *router.Route) (router.LogAdapter, error) {

        format := getopt("SYSLOG_FORMAT", "rfc5424")
        priority := getopt("SYSLOG_PRIORITY", "{{.Priority}}")
-       hostname := getopt("SYSLOG_HOSTNAME", "{{.Container.Config.Hostname}}")
        pid := getopt("SYSLOG_PID", "{{.Container.State.Pid}}")
+
+       b, err := ioutil.ReadFile("/etc/host_hostname") // just pass the file name
+       if err != nil {
+               hostname = getopt("SYSLOG_HOSTNAME", "{{.Container.Config.Hostname}}")
+       } else {
+               hostname = string(b) // convert content to a 'string'
+       }
        tag := getopt("SYSLOG_TAG", "{{.ContainerName}}"+route.Options["append_tag"])
        structuredData := getopt("SYSLOG_STRUCTURED_DATA", "")
        if route.Options["structured_data"] != "" {
[root@svt2-ucp01 logspout]#

**Comment by almereyda** [comment]
So as #329 has been merged, this can be closed?
