### ISSUE TITLE
Log to Papertrail with Container Name instead of ID

### ISSUE THREAD

**Issue by chspr** [gliderlabs/logspout#339]
I'm running a dockerised application and use a logspout container to send the logs to papertrailapp.com

Now the containers of my application always keep the same name but their IDs change after each new release. Is there a way to send the logs to papertrail using the the name of the container as sender/source instead of its ID (which seems to be the default behaviour)?

Any help is appreciated!

**Comment by Applemann** [comment]
@chspr you need change hostname of your container (default is container ID)

**Comment by chspr** [comment]
I'm not exactly sure what you mean. Containers do always have names, right? If you don't specify it explicitly, it gets assigned some random name like "jolly_unicorn". I have my containers all named explicitly. I'm looking for a way to use that name as an identifier (instead of the container ID that is beeing sent right now) when logs are sent to papertrail.

Can you please explain how I would go about changing the hostname?

Thank you.

**Comment by almereyda** [comment]
Depending on how you start your containers, you can search for `hostname` on these pages:

* https://docs.docker.com/engine/reference/commandline/run/
* https://docs.docker.com/compose/compose-file/#domainname-hostname-ipc-mac_address-privileged-read_only-shm_size-stdin_open-tty-user-working_dir

**Comment by chspr** [comment]
For some reason I just assumed the hostname would default to the service-name defined in docker-compose.yml (or the docker run --name). Don't know why I never thought of setting the hostname itself explicitly. Thanks for your help, I'll know after the next release of our platform if this resolved the issue.
I'll close the issue if that'll be the case.
