### ISSUE TITLE
A way to get docker container's labels into logspout output?

### ISSUE THREAD

**Issue by uriklagnes** [gliderlabs/logspout#343]
Is there a way to get logspout to read container labels and include them in the aggregated log output?

**Comment by hanscees** [comment]
seems like a bug? 

readme says:

SYSLOG_TAG - datum for tag field (default {{.ContainerName}}+route.Options["append_tag"])

but it actually logs using tags with containerID, not with containerName.


## on my syslog-ng host:
root@core ~# ls -all /var/lib/docker/volumes/syslogng_syslog-ng_logs/_data/dock1-66/
-rw------- 1 root root   1051 Oct 27 20:55 3c820a716068.log
-rw------- 1 root root    645 Oct 27 21:41 7870114ebc5f.log
-rw------- 1 root root   1128 Oct 27 20:52 9c3e5170d83d.log

####the sending docker host with containERS:
docker ps
CONTAINER ID        IMAGE                        COMMAND                  CREATED             STATUS              PORTS                  NAMES
7870114ebc5f        gliderlabs/logspout:latest   "/bin/logspout sys..."   9 minutes ago       Up 9 minutes        80/tcp                 logspout2017-10-27
3c820a716068        ntpupd_ntp                   "/usr/bin/chronyd.sh"    23 hours ago        Up About an hour    0.0.0.0:123->123/udp   ntp2017-09-29
aa48babb0482        nextcloud                    "/entrypoint.sh ap..."   4 days ago          Up About an hour    0.0.0.0:8080->80/tcp   nextcloud2017-10-2

**Comment by markdascher** [comment]
`{{.Container.Config.Labels.abc}}` will do it. Or `{{index .Container.Config.Labels "a.b.c"}}` if the label has dots in it.

**Comment by michaelshobbs** [comment]
fix provided
