### ISSUE TITLE
Are you going to cut a release soon?

### ISSUE THREAD

**Issue by chris7444** [gliderlabs/logspout#354]
Last release I see on hub.docker.com is v3.2.3. There is one feature I would like to see in a release  which is the one documented in [issue 328](https://github.com/gliderlabs/logspout/issues/328) (run logspout as a global service)

Currently we need to pull the image with the 'master' tag which, by definition  may not be as stable as a release

When do you think you will be cutting a release ?

Sorry of this is not the appropriate way for asking a question

**Comment by michaelshobbs** [comment]
I'll see what I can do. You can check out our [slack](https://glider-slackin.herokuapp.com/) for questions like this in the future.
