### ISSUE TITLE
Logstash should run before logspout in docker-compose

### ISSUE THREAD

**Issue by dvyas** [gliderlabs/logspout#361]
Hi,

I am writing docker-compose yml file for logspout and ELK stack. The condition is that logstash should be up and in listening mode before logspout start otherwise it keeps reconnecting. 
Any one has idea about this?

**Comment by kingjerod** [comment]
https://docs.docker.com/compose/compose-file/#depends_on

**Comment by michaelshobbs** [comment]
Docs noted. Closing this issue
