### ISSUE TITLE
New release?

### ISSUE THREAD

**Issue by discordianfish** [gliderlabs/logspout#372]
Hi,

I need toJSON and it didn't seem to be included in the latest release yet. It's only available in the 'latest' docker image and I'd like to avoid using that.

Could you do a new release including a tagged docker image for that?

**Comment by michaelshobbs** [comment]
I'll have a look today

**Comment by discordianfish** [comment]
Great, thanks! I also realize that 'latest' is only still using v3.2.3 not the code in master, so there doesn't seem to be any docker image with toJSON currently?

**Comment by michaelshobbs** [comment]
We build a master tag off of....well, master as well. 😁

**Comment by michaelshobbs** [comment]
releasing now
