### ISSUE TITLE
3.2.4 causing issues with custom docker builds?

### ISSUE THREAD

**Issue by billimek** [gliderlabs/logspout#374]
No idea if this is related, but I have automated docker builds configured to trigger whenever there is a new `gliderlabs/logspout` docker image pushed to docker hub.

My image builds from https://github.com/gliderlabs/logspout/blob/master/custom/Dockerfile on docker hub via automated builds.  It works on my local, but is failing on docker hub now:

```
Building in Docker Cloud's infrastructure...
Cloning into '.'...

KernelVersion: 4.4.0-93-generic
Arch: amd64
BuildTime: 2017-08-17T22:50:04.828747906+00:00
ApiVersion: 1.30
Version: 17.06.1-ce
MinAPIVersion: 1.12
GitCommit: 874a737
Os: linux
GoVersion: go1.8.3
Starting build of index.docker.io/billimek/logspout:gelf...
Step 1/2 : FROM gliderlabs/logspout:master

[91m# Executing 3 build triggers...
[0m
Step 1/1 : COPY ./build.sh /src/build.sh

Step 1/1 : COPY ./modules.go /src/modules.go

Step 1/1 : RUN cd /src && chmod +x ./build.sh && ./build.sh "$(cat VERSION)-custom"

 ---> Running in f395c450159e

[91m/bin/sh: ./build.sh: Text file busy
[0m
Removing intermediate container 75197530001b

Removing intermediate container f395c450159e

Removing intermediate container 0eda008907ff

The command '/bin/sh -c cd /src && chmod +x ./build.sh && ./build.sh "$(cat VERSION)-custom"' returned a non-zero code: 2
```

[build log](https://hub.docker.com/r/billimek/logspout/builds/bwa9fql7whhkcbegjpbqtnk/).

Given that the error is about `./build.sh: Text file busy` I wonder if the change to `chmod +x ./build.sh` is somehow inexplicably causing this failure?

**Comment by michaelshobbs** [comment]
hrm we build a custom image from the `custom/` dir in CI. definitely open to accepting a PR to fix this

**Comment by billimek** [comment]
I found this which suggests it's a docker hub issue: https://github.com/moby/moby/issues/13594

Investigating a workaround and will PR if necessary or close this issue.  Look for a followup from me soon!

**Comment by billimek** [comment]
#375 created to fix this.  The `sync` alone didn't seem to do the trick, so used a combination of a `sleep 1` & `sync`.

**Comment by tobiasfielitz** [comment]
Same issue over here. Merge pls.
