### ISSUE TITLE
include backlog of already running containers?

### ISSUE THREAD

**Issue by localghost** [gliderlabs/logspout#390]
Currently, if logspout is started when some other containers are already running it won't retrieve logs of the other containers logged between start of those containers up to the start of logspout. Is there a reason logspout doesn't treat already running containers the same way as restarted containers, i.e. can't it retrieve all logs of already running containers if `BACKLOG=true`.

I believe this could be a one-line change in `pump.go`, from:
```
		p.pumpLogs(&docker.APIEvents{
			ID:     normalID(listing.ID),
			Status: "start",
		}, false, inactivityTimeout)
```
to:
```
		p.pumpLogs(&docker.APIEvents{
			ID:     normalID(listing.ID),
			Status: "start",
		}, backlog(), inactivityTimeout)
```
but maybe there is a reason why it hasn't been done already?

**Comment by merowing1279** [comment]
Did a change:
https://github.com/gliderlabs/logspout/pull/511
