### ISSUE TITLE
How Do I Debug Logspout?

### ISSUE THREAD

**Issue by jdgiotta** [gliderlabs/logspout#399]
I'm running a custom build for logstash module, but I'm not seeing an logs from other containers being "spouted" to the ELK stack.

The log output of the spout docker image doesn't show any errors

> \# logspout v3.2.5-custom by gliderlabs
> \# adapters: syslog raw tcp udp logstash
> \# options : persist:/mnt/routes
> \# jobs    : pump routes http[]:80
> \# routes  :
> \#   ADAPTER     ADDRESS                         CONTAINERS      SOURCES OPTIONS
> \#   logstash+tcplogger_service_logstash_1:5000                          map[]

Is there a way to debug the image to know if it is connecting and listening appropriately?

**Comment by jdgiotta** [comment]
Also, I'm publishing, but all I get are 404s when accessing http://localhost:8000/logs

**Comment by michaelshobbs** [comment]
passing the `DEBUG` env variable to the logspout container might help here

https://github.com/gliderlabs/logspout#environment-variables

**Comment by michaelshobbs** [comment]
Feel free to join the gliderlabs slack for more assistance if needed

**Comment by jdgiotta** [comment]
Yeah, I'd be interested in joining the slack. DEBUG shows me that added container events are happening, but otherwise nothing sent out from the tail
