### ISSUE TITLE
Connection refused when using Go upd server

### ISSUE THREAD

**Issue by barell** [gliderlabs/logspout#407]
Hello,

I'm trying to use logspout and process some logs using go. Below is my udp server which should print any incoming messages from logspout.

I run both, logspout and the code below in two docker containers and I can successfully ping from inside, so they are definitely accessible.

The error I got from logspout is

> logspout_1  | 2018/08/01 16:16:43 syslog: write udp 172.26.0.2:5869: connection refused

Is there anything I'm doing wrong?

```
package main

import (
	"net"
	"fmt"
	"log"
)

func handleData(conn *net.UDPConn) {
	var buf [1024]byte

	n, _, err := conn.ReadFromUDP(buf[0:])

	if err != nil {
		log.Println(err)

		return
	}

	msg := string(buf[0:n])

	fmt.Println(msg)
}

func main() {

	addr := net.UDPAddr{
		IP:net.IP{127, 0, 0, 1},
		Port:5869,
	}

	conn, err := net.ListenUDP("udp", &addr)
	if err != nil {
		fmt.Println(err)
		return
	}
	defer conn.Close()

	for {
		handleData(conn)
	}
}
```

**Comment by gbolo** [comment]
@barell don't bind to 127.0.0.1 and instead bind to all interfaces so that the other docker container can reach it

**Comment by gbolo** [comment]
@barell please close this issue if my comment has resolved it.

Thanks

**Comment by gbolo** [comment]
closing issue, as the problem was most likely due to binding to `127.0.0.1`

**Comment by barell** [comment]
@gbolo sorry for delayed response. I couldn't get around to test it again.

You were right, I have updated the UDPAddr IP from 127.0.0.1 to 0.0.0.0 and it worked.

Thank you!
