### ISSUE TITLE
How to pass old logs of servers after papertrail maintenance?

### ISSUE THREAD

**Issue by kycfeel** [gliderlabs/logspout#414]
Hey there. I'm using logspout to pass logs of kubernetes services to papertrail. 

One question. Is it possible to set logspout to pass old logs of servers after papertrail maintenance? (or logspout disconnection) 

Papertrail was under maintenance last few hours today, and I realized some of logs are missing.

Many thanks.

**Comment by gbolo** [comment]
Hi @kycfeel 

It is not currently part of the logspout design to send previous logs. It is a real-time only solution.
