### ISSUE TITLE
Using multiline together with logtash adapter

### ISSUE THREAD

**Issue by tiagoReichert** [gliderlabs/logspout#415]
I'm trying to use the Multiline functionality of logspout together with the logstash adapter.
However, I get following error message:
```
9/10/2018 1:32:59 PM# logspout v3.2.5 by gliderlabs
9/10/2018 1:32:59 PM# adapters: syslog multiline tcp udp tls raw
9/10/2018 1:32:59 PM# options : persist:/mnt/routes
9/10/2018 1:32:59 PM!! bad adapter: multiline+logstash
```
with RAW it seems to be working fine:
```
9/10/2018 1:30:25 PM# logspout v3.2.5 by gliderlabs
9/10/2018 1:30:25 PM# adapters: udp tls raw syslog multiline tcp
9/10/2018 1:30:25 PM# options : persist:/mnt/routes
9/10/2018 1:30:25 PM# jobs    : pump routes http[routes,logs]:80
9/10/2018 1:30:25 PM# routes  :
9/10/2018 1:30:25 PM#   ADAPTER		ADDRESS				CONTAINERS	SOURCES	OPTIONS
9/10/2018 1:30:25 PM#   multiline+raw	logstash-searchguard:5000				map[]
```

Is it really not supported to be used togheter with logstash?

**Comment by tiagoReichert** [comment]
The official gliderlabs/logspout container does not have support to Logstash, therefore, I got this error.

Solution: Created a container with Logspout, Logstash, and Multiline: tiagoreichert/logspout-logstash-multiline

**Comment by sritedd** [comment]
can u elaborate the solution please.. i want to have an adapter with multiline+raw+syslog
