### ISSUE TITLE
Relic with contiki

### ISSUE THREAD

**Issue by viallykaz** [gliderlabs/logspout#423]
Hello dear all,

I am beginner in contiki and I want to implement Ed25519 algorithm using Relic toolkit, I already installed contiki and and downloaded relic in relic-master and built it in contiki-2.7/MyProject/relic-target as described in https://code.google.com/archive/p/relic-toolkit/wikis/BuildInstructions.wiki

And then I created a new folder called MyProject-relic in contiki examples folder, where I created the RelicTest1.c and the Makefile and then I added these below lines in Makefile.include from contiki-2.7 folder:

RELIC_SOURCE = ../../MyProject/relic-master
RELIC_TARGET = ../../MyProject/relic-target

CFLAGS+= -|$(RELIC_SOURCE)/include -|$(RELIC_TARGET)/include -Os
PROJECT_LIBRARIES+= $(RELIC_TARGET)/lib/librelic_s.a

When I go to my MyProject-relic folder and try to compile RelicTest1.c I get these error:

TARGET not defined, using target 'native'
CC ../../core/net/rime/rimeaddr.c
/bin/sh: 1: ../../MyProject/relic-target/include: Permission denied
/bin/sh: 1: ../../MyProject/relic-master/include: Permission denied
cc: error: -E or -x required when input is from standard input
make: *** [obj_native/rimeaddr.o] Error 126

I tried to run chmod, chown to give permission everywhere but nothing happens, I can't move forward, I really need help in order to solve my problem.

Any help or recommandation will be highly appreciated :) :)

Thank you

Best Regards;

Vially

**Comment by michaelshobbs** [comment]
this is the `gliderlabs/logspout`. i'm not sure what `logspout` has to do with `contiki` *or* `relic`. closing as i think this was opened by mistake but if this does somehow have to do with `logspout`, i'll reopen.

**Comment by viallykaz** [comment]
Thank you dear Michael,
I think you might be right!
Could you help me how to deal with this issue?

Thanks 

Best Regards
Vially
