### ISSUE TITLE
Disable namespace remapping

### ISSUE THREAD

**Issue by tomlankhorst** [gliderlabs/logspout#424]
This is an issue to help anyone looking to solve the following permission error. 

`yyyy/mm/dd hh:MM:ss pump ended: Get http://unix.sock/containers/json: dial unix /var/run/docker.sock: permission denied`

The container might not be able to bind `/var/run/docker.sock` when docker namespace remapping is enabled. 
So instruct docker to start this `logspout` container without remapping by adding the following flag: 
`--userns=host`

How about adding this to the documentation?

**Comment by josegonzalez** [comment]
Pull requests welcome @tomlankhorst :)

**Comment by tomlankhorst** [comment]
@josegonzalez Sure #425

**Comment by josegonzalez** [comment]
Closing as there is a pull request open.
