### ISSUE TITLE
How to send logs securely to logentries using logspout?

### ISSUE THREAD

**Issue by jamoham** [gliderlabs/logspout#433]
**Problem**
We have been using `logspout` to send our logs to logentries.

We realized that these logs are being sent on an insecure channel and we are now trying to follow this approach to make the transport secure:
https://docs.logentries.com/docs/input-plaintcpudp#section-secure-transport

This approach asks for the following 2 changes to make it send over encrypted channel:
1. Add 10000 to the port number. Example: If the port assigned is 12345, then use 22345
2. Change the domain from `data.logentries.com` to `api.logentries.com`

But this approach is not working and we don't see any logs.

**Debugging**
1. There are no errors seen in logspout logs:
```
# logspout v3.2.6 by gliderlabs

# adapters: multiline tcp udp tls raw syslog

# options : persist:/mnt/routes

# jobs    : routes http[health,logs,routes]:80 pump

# routes  :

#   ADAPTER        ADDRESS            CONTAINERS    SOURCES  OPTIONS

#   multiline+raw api.logentries.com:22345  'CONTAINER_NAME'     map[]
```

2. We have verified that using `telnet-ssl`, we are able to send logs to `api.logentries.com:22345` from the above-mentioned container 'CONTAINER_NAME'

Please let me know if you need any information.

**Comment by gbolo** [comment]
have you tried sending with `tcp+tls://api.logentries.com:22345`?

**Comment by gbolo** [comment]
@jamoham please confirm if you have tried the above. We would like to close stale issues.

**Comment by jamoham** [comment]
@gbolo 

When I try api.logentries.com:22166`
I get the following error:
```
#   ADAPTER	ADDRESS			CONTAINERS	SOURCES	OPTIONS
#   raw+tcp	api.logentries.com:22166*locust*		map[]
2019/03/04 03:11:42 raw: write tcp 35.0.1.59:58160->54.217.226.43:22166: write: broken pipe
2019/03/04 03:11:42 routes ended: %!s(<nil>)
```

As we have been using `multiline+raw`,I tried using `multiline+raw+tls`:
```
# routes  :
#   ADAPTER		ADDRESS			CONTAINERS	SOURCES	OPTIONS
#   multiline+raw+tls	api.logentries.com:22166*locust*		map[]
```

The logs start to show up in logentries but here multiple log lines are being clubbed together in the same line in logentries.

We are setting `RAW_FORMAT` to `'[{{ .Container.Config.Hostname }}] {{ toJSON .Data }}'`

**Comment by gbolo** [comment]
@jamoham 

As your logs are now showing up (by simply adding `tls` to address) this issue is now resolved. Furthermore, you may want to add `\n` to the end of your `RAW_FORMAT`

**Comment by mattpetrick** [comment]
> Furthermore, you may want to add `\n` to the end of your `RAW_FORMAT`

tested adding the line break but it is not being honored - multiple log lines are being clubbed together now with a `\n` between them.

**Comment by normelton** [comment]
If anyone else is struggling to get a newline into their docker-compose config, here's a tip:

```
    environment:
      RAW_FORMAT: >
        {{ toJSON .Container }}
```
