### ISSUE TITLE
Not logging one-off containers

### ISSUE THREAD

**Issue by guidolodetti** [gliderlabs/logspout#436]
Hi!

I run a cron task from a dokku app with the following command:

`dokku --rm run APP node FILE.`

Unfortunately, logs are printed and I can see them, but Logspout seems not to be catching them. I already have other applications and all of them work correctly with Logspout!

Is it something related to the command `node FILE.js`?

Thanks!

EDIT: The same is if I do `dokku enter APP` and then `node FILE.js!`

**Comment by michaelshobbs** [comment]
Per the [logspout documentation](https://github.com/gliderlabs/logspout#route-all-container-output-to-remote-syslog):

> logspout will gather logs from other containers that are started *without the `-t` option* and are configured with a logging driver that works with docker logs (journald and json-file).

Without more information, my guess is that `dokku` is adding the `-t` option.

**Comment by guidolodetti** [comment]
Hello,

the executed docker container command is `/exec node FILE.js`. As I previously said, it is like it's something related to executing the pure JS file, because other containers/apps/commands correctly work.

**Comment by michaelshobbs** [comment]
To clarify specifically, do other containers started via `dokku --rm run APP` log correctly?

**Comment by guidolodetti** [comment]
I have just found that Dokku logging works well with automatic cronjobs, but won't work if I manually invoke the commands with the CLI! Thanks for your help and sorry for the useless issue!
