### ISSUE TITLE
Using Logspout on a Synology using `db` logging driver

### ISSUE THREAD

**Issue by edorgeville** [gliderlabs/logspout#455]
Hi,
I am trying to get Logspout working in a Synology NAS environment, but the following requirement seems to be an issue:
> logspout will gather logs from other containers that [...] are configured with a logging driver that works with docker logs (`journald` and `json-file`).

By default, Synology's Docker uses the `db` logging driver. Yet, `docker logs` still works. Portainer also seems to be able to read and stream logs.
After testing, the Synology DSM doesn't seem to like changing the logging driver to `json-file`. It breaks the friendly UI, listing running containers, stats, etc.

Is there a way to force Logspout to gather logs from containers using the `db` logging driver? 
Thank you! 🤗

**Comment by edorgeville** [comment]
Well, that was simpler than expected. Changing this line:
https://github.com/gliderlabs/logspout/blob/0845b6ee9c94e18bbc292ac817c44bfe1d9c762d/router/pump.go#L77
to
```go
 case "json-file", "journald", "db": 
```  
Works perfectly. Maybe this could become an environment variable?

**Comment by michaelshobbs** [comment]
Added in [v3.2.9](https://github.com/gliderlabs/logspout/compare/v3.2.8...v3.2.9)
