### ISSUE TITLE
VirusTotal says this image contain coinminer

### ISSUE THREAD

**Issue by Randomneo** [gliderlabs/logspout#487]
Actions to reproduce
    
    docker pull gliderlabs/logspout
    docker save gliderlabs/logspout > logspout.tar

upload this tar to [virustotal](https://virustotal.com). Screen attached
![virustotal](https://user-images.githubusercontent.com/10756368/96125364-64c34b80-0efc-11eb-9d71-a71862db9064.png)

**Comment by michaelshobbs** [comment]
Confirmed building locally and uploading that to VirusTotal yields the same result. However, Kaskersky doesn't report anything. I wonder if this is a false-positive from VirusTotal.

<img width="1654" alt="Screen Shot 2020-10-15 at 07 28 19" src="https://user-images.githubusercontent.com/4491438/96143606-19874980-0eb8-11eb-916d-08465917b03b.png">

**Comment by alex-vasilchenko-md** [comment]
Btw, there is no such issue in previous versions.

**Comment by michaelshobbs** [comment]
I exported the filesystem of a running container based on that image and scanned it. VirusTotal detects the same issue but won't show me file where it detected the ad-aware....

**Comment by michaelshobbs** [comment]
Any help in locating the root cause here would be greatly appreciated

**Comment by michaelshobbs** [comment]
I think #490 resolves this.

https://www.virustotal.com/gui/file-analysis/OGQxMTE3YTM0MzQxYjcwZTM4M2FmZTlhNTE0YjE5NDg6MTYwMzM4MzQyMA==/detection
```
docker pull gliderlabs/logspout:master
docker save gliderlabs/logspout:master > logspout_master.tar
```

<img width="1282" alt="Screen Shot 2020-10-22 at 09 18 36" src="https://user-images.githubusercontent.com/4491438/96901116-b19caa00-1447-11eb-9a6e-ed26bb03a653.png">

**Comment by michaelshobbs** [comment]
releasing this as v3.2.12. image up soon
