### ISSUE TITLE
always listening on port 80

### ISSUE THREAD

**Issue by ausfestivus** [gliderlabs/logspout#488]
Im trying to run logspout so it doesn't listen on port 80 at all. There is another container already listening on port 80 which I cannot change.

Im starting the logspout container with the following command:

`sudo docker run --userns=host --restart=unless-stopped -d -p 127.0.0.1:8888:8888 --name="logspout" -e 'BACKLOG=false' -e 'PORT=8888' -e 'HTTP_BIND_ADDRESS=127.0.0.1' --volume=/var/run/docker.sock:/var/run/docker.sock gliderlabs/logspout syslog://10.0.1.229:514`

When I look at the list of things running on port 80 in docker:

```
sudo docker container ls --format "table {{.ID}}\t{{.Names}}\t{{.Ports}}" -a | grep 80
f1aff0d2dab6        logspout                    80/tcp, 127.0.0.1:8888->8888/tcp
f8f70b5c75c3        app_nginx                  0.0.0.0:80->80/tcp, 0.0.0.0:443->443/tcp, 0.0.0.0:23001->8080/tcp
a408158ef4c8        replicated-premkit          80/tcp, 443/tcp, 2080/tcp, 0.0.0.0:9880->2443/tcp
```

So, it seems, despite my `docker run` command when starting logspout that it's always listening on port 80.

Im not super knowledgable about docker and its networking so its entirely possible im not doing something right in the `docker run` command for logspout. Feel free to wield the cluebat.

**Comment by claustres** [comment]
logspout is always listening on 80 **inside** your container, and with Docker there is no problem if another container also listen to 80 internally. A problem could arise if you'd like to expose the port of the container on your host, what is done using the `-p` option. So if you'd like to expose logspout on your host on a different port (eg 81) you should do `-p 127.0.0.1:80:81`, there is usually no need to use `PORT`.

**Comment by ausfestivus** [comment]
Thanks for the clarification @claustres. 

Turns out the issue im seeing further up the stack is actually related to a different problem in another container/component. What I thought was a behaviour problem with logspout wasnt one at all.
