### ISSUE TITLE
BACKLOG environnement variable inverted since v3.2.7

### ISSUE THREAD

**Issue by jonenst** [gliderlabs/logspout#494]
https://github.com/gliderlabs/logspout/commit/621524edba170d901
```diff
 func backlog() bool {
-       if os.Getenv("BACKLOG") == "false" {
-               return false
-       }
-       return true
+       return os.Getenv("BACKLOG") == "false"
 }
```

Since v3.2.7 you have to set BACKLOG=false to get the backlog...

**Comment by michaelshobbs** [comment]
Thanks for the heads up. I've corrected this and added tests

**Comment by jonenst** [comment]
cool, thanks for the quick fix!
