### ISSUE TITLE
Require image for ARM64 architecture

### ISSUE THREAD

**Issue by odidev** [gliderlabs/logspout#499]
Hi Team,

I am trying to use **gliderlabs/logspout** on ARM64 architecture but it seems the arm64 tag is not available in Docker Hub.

I have done the below changes in order to use buildx to build and push the image for arm64 and amd64 to dockerhub through circle-ci.

**Commit Link** - https://github.com/odidev/logspout/commit/01186b1a6e8fbcb15082808525d3c55bc2693c24

**Dockerhub Link** - https://hub.docker.com/repository/docker/odidev/logspout

**Circle-ci Link** - 
https://app.circleci.com/pipelines/github/odidev/logspout/2/workflows/a1cca5eb-6140-4bbc-b382-347d932a6655

Please share your thoughts on this, and if the changes look good will raise a PR.

**Comment by odidev** [comment]
I have raised a [PR](https://github.com/gliderlabs/logspout/pull/505). Could you please review this PR.

**Comment by jonathantullett** [comment]
@michaelshobbs - could this get a review? It would be great to have logspout built for ARM so it can run on raspberry pi docker servers.

Thank you.

**Comment by michaelshobbs** [comment]
reviewed. that PR never ran through CI and it wasn't fully fleshed out. apologies for not reviewing earlier as i've been pulled away from the open source side of things.
