### ISSUE TITLE
redis as destination

### ISSUE THREAD

**Issue by cgswong** [gliderlabs/logspout#50]
I've been trying to send logs to redis using:
```
docker run -v=/var/run/docker.sock:/tmp/docker.sock -h $HOSTNAME -p 8000:8000 gliderlabs/logspout redis://redis.host.com:6379
```
Any time frame on when having redis as a destination will be included?

**Comment by progrium** [comment]
I don't believe we will support it natively for now, but track this PR to see if they release it as a third party module:
https://github.com/gliderlabs/logspout/pull/41

**Comment by rtoma** [comment]
@cgswong maybe https://github.com/rtoma/logspout-redis-logstash fits your usecase?
