### ISSUE TITLE
Add ARM support for raspberrypi

### ISSUE THREAD

**Issue by benisai** [gliderlabs/logspout#508]
Hello,
Docker runs on arm architecture but this image does not. Can you recompile this for ARM.

**Comment by rasmuslp** [comment]
I would also really like to try this on Raspberry Pis of various types. I see that `linux/arm64` support was added in #512. Would it be as simple as adding another platform for `linux/arm/v6` ?

**Comment by michaelshobbs** [comment]
Probably? Feel free to open a PR with it added
