### ISSUE TITLE
[question] Logo usage for Home Assistant Logspout add-on

### ISSUE THREAD

**Issue by bertbaron** [gliderlabs/logspout#515]
I just created a Logspout add-on for Home Assistant (https://github.com/bertbaron/hassio-addons/tree/main/logspout). Is it ok if I use your github avatar logo for it? It looks quite nice and I saw it already being used by some other resources about Logspout on the internet. I must admit that I already added the logo but I'll of course remove it if you're not ok with it.

**Comment by bertbaron** [comment]
This logo:
![image](https://user-images.githubusercontent.com/9292223/163363672-9ce79e6f-4c3d-4b0a-9e17-3de5cda91e47.png)

**Comment by josegonzalez** [comment]
Just want to call out that this is the gliderlabs logo, not the logspout logo.

**Comment by bertbaron** [comment]
Yes, I know. But it looks great and I didn't see any Logspout specific logo. Of course I can try to come up with something else  but If you're ok with this logo and don't have another suggestion then I prefer to leave it like this.

**Comment by josegonzalez** [comment]
I'm fine with it, but I don't own the logo. I don't think @progrium would mind though.

**Comment by progrium** [comment]
sounds fine!

**Comment by bertbaron** [comment]
Thanks, I'll close this issue then.
