### ISSUE TITLE
Routes not working

### ISSUE THREAD

**Issue by epelc** [gliderlabs/logspout#52]
It appears that routes do not work at all. I've tried restart/rerunning my containers and adding/removing the routes several times. The only way it works is if I log all routes by specifying a syslog server as an arg to the container.

Example route
```
{
    "source": {
        "name": "myapp",
        "types": ["stdout","stderr"]
    },
    "target": {
        "type": "syslog",
        "addr": "logstash:514"
    }
}
```
I've tried with/without source types, using prefix and filter instead of name, adding a port to the addr/with no port, and also adding `syslog://` to the address.

Any help would be greatly appropriated. It's very hard to test this locally if your also running kibana/elasticsearch in a container with the default to all routes.

**Comment by progrium** [comment]
What version? Master?

**Comment by epelc** [comment]
@progrium the `latest` tag in docker which I think routes to release.

**Comment by epelc** [comment]
@progrium Also the read me still references the old docker image(progrium/logspout) a couple of times

**Comment by progrium** [comment]
Can you try against master? Keep in mind the route serialization format changed for the api.

**Comment by nagliyvred** [comment]
I have the same problem with the latest image. When trying to use master I get: 
```
[logspout-2] 2015-04-02T03:00:31.463781095Z 2015/04/02 03:00:31 pump ended: dial unix /var/run/docker.sock: no such file or directory
```

**Comment by progrium** [comment]
I don't believe that's the same issue @nagliyvred but I just pushed a fix to master if you want to try that again. Docs are updated too to use new path for mounting docker socket. But old one works now too.

**Comment by nagliyvred** [comment]
Thanks @progrium, now it does not fail with that error anymore.
