### ISSUE TITLE
An exclude option supports

### ISSUE THREAD

**Issue by heycalmdown** [gliderlabs/logspout#59]
If I have some containers which is I don't want to grab logs and routes into somewhere because they have their own log sending mechanism, having a simple exclude option would be nice. It could take a regexp pattern to match each container name or something, like `-e EXCLUDE_PATTERN=[(mongod)|(redis)]`...

**Comment by heycalmdown** [comment]
I just found custom routes. It'd be an answer.

**Comment by jmmills** [comment]
This is still a useful feature when dealing with sending logs to containers that generate logs as a start-up incantation from a composing system (like docker compose or fig)...

**Comment by mgood** [comment]
For future readers, as you mentioned on #95, the standard solution is to start the container with this option to tell logspout to ignore it:

    $ docker run -d -e 'LOGSPOUT=ignore' image

**Comment by jmmills** [comment]
Yeah, I ran into a version issue... you may want to update your docker image... it's still on version 2 in which this feature doesn't exist.
