### ISSUE TITLE
Option to specify program name per container

### ISSUE THREAD

**Issue by renfredxh** [gliderlabs/logspout#63]
It'd be awesome if there were a way to specify the program name per docker container via environment variables inside the container (similar to how you can set the `LOGSPOUT=ignore` variable inside a container) that tells logspout what name to give it when routing the log.

**Use cases:**

If you're using a container orchestration service (Tutum, Flynn, Dokku) in some cases you may have no control over the `--name` option of your containers when they're deployed. For example, Tutum assigns a GUID to the name field of each container you deploy. So when using logspout my logs in papertrail end up looking like this: 
![log example](https://cloud.githubusercontent.com/assets/3800339/6830793/8d9e93f8-d2f2-11e4-9362-8dbf7ef0fd90.png)
Note the program labels such as `f0d9d99a-18e0-4097-91fd-1e496a451cd0` which are automatically assigned by Tutum aren't helpful, since they have no semantic meaning and change on each deploy. If I could specify an variable `LOGSPOUT_NAME=my-containers-app` in the container and have logspout use that instead then it would be much easier to filter logs this way.

Even if you do have control over container names, you might want to group them in a custom way. If you have multiple instances of the same service running each container has to have a unique name. So you might end up giving the names `app-container-1`, `app-container-2` in Docker, but want to have all the logs appear under the name `app-container` for simplicity. 

Not sure if it's possible, but I think it'd be a very useful feature to have.

**Comment by progrium** [comment]
In this scenario, are you running logspout or is the platform?

**Comment by renfredxh** [comment]
I'm running logspout on the platform. More specifics are in the [guide](http://blog.tutum.co/2015/03/19/log-forwarding-with-tutum/) they released.

**Comment by progrium** [comment]
I ask because that means if you have control over the logspout container, you could potentially solve this by configuring logspout once to use a different value. Logspout in master supports this with configurable syslog value templates.

**Comment by renfredxh** [comment]
I played around with the [configurable options](https://github.com/gliderlabs/logspout/blob/7a4ab92e5a0b0cf677f8a6b3424cc2d1cd44b535/adapters/syslog/syslog.go#L39-L48) in syslog.go and found something that works well for my specific setup. For anyone curious, the options I set were:

```
SYSLOG_FORMAT=rfc3164
SYSLOG_HOSTNAME=<hostname of my server>
SYSLOG_TAG={{.Container.Config.Hostname}}
```

Since on my container orchestration platform I have control over setting the hostname for each container, I can use that as the syslog tag and the result is [much prettier logs](https://i.imgur.com/52O95aN.png).

If these changes eventually merged into release then I should be set. Thanks for pointing me in the right direction!

**Comment by progrium** [comment]
Glad they work for you. Should we close this?

**Comment by ypadlyak** [comment]
@renfredxh It there way to get this in dokku-logspout before released? How do I make it use the master version of logspout?

**Comment by jgallen23** [comment]
Running into a similar issue. Is there any way to configure this with ENV vars or do I need to build my own version of logspout to set these?

**Comment by jgallen23** [comment]
got it working by setting `-e SYSLOG_HOSTNAME=myhost` when I created the logspout container
