### ISSUE TITLE
Container build does not compile custom modules

### ISSUE THREAD

**Issue by maxpersson** [gliderlabs/logspout#69]
The `RUN` command in the Dockerfile (https://github.com/gliderlabs/logspout/blob/master/Dockerfile#L8) needs to be prefixed with `ONBUILD` to actually run custom module builds. I'll submit a PR that fixes this.

**Comment by progrium** [comment]
This should be the full solution. Let me know:
https://github.com/gliderlabs/logspout/pull/73

**Comment by maxpersson** [comment]
Works fine! Thanks again, this solves log forwarding really nicely for us now!
