### ISSUE TITLE
stdout of container w/ TTY not captured

### ISSUE THREAD

**Issue by tobowers** [gliderlabs/logspout#72]
I have a centos:centos6 container running with /bin/bash -l and I'm trying to see `echo "hi"` logged to logstash through logspout.

I start the centos container like so:  `docker run --rm -it centos:centos6 /bin/bash -l` and then I `echo "hi"`

I have ELK + Logspout running with the following docker-compose: https://gist.github.com/tobowers/b9eb3d7291399440e976#file-docker-compose-yml

We've tested sending syslog events to logstash and seeing them logged.

After logspout starts up, I would expect to see the stdout from the echo hi appearing as a syslog message in logstash, but I see nothing.

`docker logs #{container_name}` (where #{container_name} is the name of the centos6 container, correctly show the stdout from the bash commands.

Did I misinterpret the point of logspout? What am I doing wrong?

**Comment by progrium** [comment]
We don't capture logs from containers started interactively with a TTY. We are going to make this configurable, but it will not be on by default.

**Comment by amacneil** [comment]
Did you ever make this configurable?
