### ISSUE TITLE
Error doing a custom build

### ISSUE THREAD

**Issue by jimmcslim** [gliderlabs/logspout#74]
Trying to do a custom build with the logstash adaptor from looplab: https://github.com/looplab/logspout-logstash

    docker build .

...in a directory with a minimal dockerfile...

    FROM gliderlabs/logspout:master

and modules.go...

    package main

    import (
            _ "github.com/gliderlabs/logspout/transports/udp"
            _ "github.com/looplab/logspout-logstash"
    )

The build mostly succeeds but ultimately fails with...

    ln: /var/run/docker.sock: File exists

Running Docker 1.5.

**Comment by progrium** [comment]
Thanks for reporting. Fixed in master just now.

https://github.com/gliderlabs/logspout/commit/103afb52311b4cb101b6ea2325ff1350371b606e
