### ISSUE TITLE
attacher: dial unix /tmp/docker.sock: no such file or directory

### ISSUE THREAD

**Issue by peebles** [gliderlabs/logspout#80]
docker run  -d   -v /var/run/docker.sock:/var/run/docker.sock     gliderlabs/logspout     syslog://$MYSERVER:3030

2015/04/09 22:25:16 attacher: dial unix /tmp/docker.sock: no such file or directory

??

**Comment by peebles** [comment]
-v /var/run/docker.sock:/tmp/docker.sock works.

**Comment by progrium** [comment]
`:master` works with both

**Comment by jmstone617** [comment]
Has the container on Docker Hub been updated with the master branch? Pulling the latest image results in the same error as above for me as of this morning.
