### ISSUE TITLE
Write to files

### ISSUE THREAD

**Issue by shazow** [gliderlabs/logspout#83]
Any plans for an adapter which writes the routed logs into their own files under a volume? Perhaps the logs could be named based on container name/id fromwhich they're routed.

This would be like a dumbed-down built-in version of running a syslogd container just to collect and write the logs.

----

> It's a mostly stateless log appliance. It's not meant for managing log files or looking at history. It is just a means to get your logs out to live somewhere else, where they belong.

Feel free to close if this is out of scope. Acknowledging that this would be somewhat contrary to the  above README statement.

**Comment by progrium** [comment]
Is it contrary? The whole point of that statement was to encourage people to avoid writing logs to disk and incur the disk IO and have to deal with complex collection/aggregation that then also has disk IO and also rotation, etc etc. Ideally you don't write logs to disk except for your aggregator. Otherwise they go over the network without touching disk. 

> It's not meant for managing [or writing] log files or looking at history [by reading log files].

**Comment by shazow** [comment]
Sure, but does logspout fall into the scope of having such an aggregator built in, or is it strict on having it re-routed to another service which will write the logs?

**Comment by progrium** [comment]
It is pretty strict on that best practice, and no aggregation is intended to be done here. Obviously people could do 3rd party modules to read/write log files, but the scope of logspout proper is intended to encourage shipping and routing log streams, not log files, to Logstash/Graylog/etc. I don't think I even want to get into reading log files. If you're stuck with log files, you treat it as a special case and use some other great tool for the job, potentially just handing them off to logspout.

**Comment by deas** [comment]
Sorry for the ignorance, just bumped into the docker logging issues. I like logspouts idea of moving the logs to some central place, but it looks like we might lose logs when the UDP service is unavailable, right? What is logspouts opinion this? Again, sorry if I missed it.
