### ISSUE TITLE
Logspout crashes when route uri contains non-default query parameters

### ISSUE THREAD

**Issue by raychaser** [gliderlabs/logspout#86]
```bash
$ docker run -v=/var/run/docker.sock:/var/run/docker.sock gliderlabs/logspout:master syslog://xxx/?hello=kitty
# logspout v3-master by gliderlabs
# adapters: raw udp tcp syslog
# options : persist:/mnt/routes
panic: runtime error: assignment to entry in nil map

goroutine 16 [running]:
runtime.panic(0x7af1c0, 0xa1e5d3)
	/usr/lib/go/src/pkg/runtime/panic.c:279 +0xf5
github.com/gliderlabs/logspout/router.(*RouteManager).AddFromUri(0xc208010d50, 0x7fff3c88ff6d, 0x19, 0x0, 0x0)
	/go/src/github.com/gliderlabs/logspout/router/routes.go:102 +0x4b3
github.com/gliderlabs/logspout/router.(*RouteManager).Setup(0xc208010d50, 0x0, 0x0)
	/go/src/github.com/gliderlabs/logspout/router/routes.go:184 +0x1bb
main.main()
	/go/src/github.com/gliderlabs/logspout/logspout.go:39 +0x646

goroutine 19 [finalizer wait]:
runtime.park(0x414ad0, 0xa22c58, 0xa20ea9)
	/usr/lib/go/src/pkg/runtime/proc.c:1369 +0x89
runtime.parkunlock(0xa22c58, 0xa20ea9)
	/usr/lib/go/src/pkg/runtime/proc.c:1385 +0x3b
runfinq()
	/usr/lib/go/src/pkg/runtime/mgc0.c:2644 +0xcf
runtime.goexit()
	/usr/lib/go/src/pkg/runtime/proc.c:1445
```

Ran into this while working on an HTTP adapter. This adapter will buffer messages to not to make too many roundtrips. I was hoping that I could expose the configuration of the buffer (size, timeout) via options (like the filter.id, ... stuff). when trying, i ran into the crash above.

The fix appears to be simple to me (but i am not a really very experienced when it comes to go...) - in routes.go, change line 83 from this:

```go
	r := &Route{
		Address: u.Host,
		Adapter: u.Scheme,
	}
```

to this:

```go
	r := &Route{
		Address: u.Host,
		Adapter: u.Scheme,
		Options: make(map[string]string),
	}
```

This works for me, but i am not sure if this is the best thing to do. If it is, happy to make a PR.

**Comment by dylanmei** [comment]
This has been called out in @nagliyvred's issue #75 and pull request #76 takes the same solution you've come up with. It's worked for me for well over a week.

**Comment by raychaser** [comment]
Thanks, @dylanmei - i should have spent the time to look at all the open issues and PRs. FWIW, the fix has been working for me as well while developing the HTTP adapter over the last couple of days. Closing this now in anticipation of #76.

**Comment by dylanmei** [comment]
Glad to hear it's working for you as well. I look forward to checking out your adapter. :)
