### ISSUE TITLE
Works with Docker 1.6?

### ISSUE THREAD

**Issue by peebles** [gliderlabs/logspout#91]
I could swear that with docker 1.5 everything was working as expected, but now with 1.6, it does not seem to send host and app over the syslog protocol:

docker run -d -v /var/run/docker.sock:/tmp/docker.sock --name logger -h s2 gliderlabs/logspout syslog://MYSERVER:514

I would expect to see "s2" as the host, and the hostname of a container as the app on the MYSERVER side.  I believe I was in 1.5, but now both are undefined or blank.

MYSERVER is using node glossy to parse messages on a udp socket, which should handle any RFC format.  I have a test-producer that uses node syslogger, which is configured for RFC5424 and it "does the right thing"

**Comment by agchillibean** [comment]
Anyone else with this issue? I'm having some troubles to make it work on Docker 1.6 :(

**Comment by progrium** [comment]
Try :master?

On Fri, May 22, 2015 at 10:51 AM, AmalioG <notifications@github.com> wrote:

> Anyone else with this issue? I'm having some troubles to make it work on
> Docker 1.6 :(
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/gliderlabs/logspout/issues/91#issuecomment-104696515>.
>



-- 
Jeff Lindsay
http://progrium.com

**Comment by agchillibean** [comment]
It works!! thank you so much for your answer and congrats for this great tool :)
