### ISSUE TITLE
PR #88 appears to have broken something in master

### ISSUE THREAD

**Issue by raychaser** [gliderlabs/logspout#92]
I noticed that after pulling master the HTTP adapter I am working on wasn't forwarding messages anymore. Thought this might be an issue on my end but couldn't figure it out. Finally, I tried with stock Logspout against Papertrail, and also, no logs appear in my account.

To reproduce locally, you can open a local TCP listener with Netcat in one terminal:

```bash
$ netcat -l 0.0.0.0 2115
```

Then `cd` to wherever you have the Logspout source code, master branch, latest (d428516f0ad80c8287ddfede5b60557344e888ae), and start Logspout:

```bash
$ DEBUG=1 ROUTE=syslog+tcp://$HOSTIP:2115 make dev
```

`$HOSTIP` is the IP of my host.

Then create some messages in a container in yet another window - I use this:

```bash
$ docker run --rm --name test ubuntu bash -c 'NEW_UUID=$(cat /dev/urandom | tr -dc 'a-zA-Z0-9' | fold -w 32 | head -n 1); for i in `seq 1 67`; do echo $NEW_UUID Hello $i; sleep .5; done'
```

I am expecting to see the test messages show up in the window running Netcat, but they don't.

However, if I roll master back to before #88 and then run Logspout again:

```bash
$ git checkout 415c0f15c790ad21515f41abe8f79a1acddadc3a
$ DEBUG=1 ROUTE=syslog+tcp://$HOSTIP:2115 make dev
```

And if I then run the message-generating container again, I see the messages I expect in the Netcat window.

When I try to same with Papertrail, things start showing up there too.

I really don't want to start a wild goose chase, but is anybody else able to reproduce this? I looked the commits in @josharian PR and rolled forward one by one, and at least for me, commit 07555c5b0bef734f45b320db262f9f3cf1626295 appears to be the culprit. Up to that point in the history of master, I get messages in the Netcat window, and as soon as I apply that commit, I suddenly don't anymore.

Looking at 07555c5b0bef734f45b320db262f9f3cf1626295 it is not at all clear to me why this is an issue. But when I change this back to wrap the call to `log.Fatalf` in a `func()` everything works again. Looking at https://golang.org/ref/spec#Go_statements this change should have been safe...

**Comment by progrium** [comment]
Yeah I would have thought it to be safe, but damn, good catch.

**Comment by josharian** [comment]
Oops. My apologies. It's a question of when the function arguments are evaluated.

**Comment by raychaser** [comment]
No worries. Thanks for the quick merge. I ran my test stuff and it is all working now! Closing.
