### ISSUE TITLE
Document  port changed from 8000 to 80

### ISSUE THREAD

**Issue by amouat** [gliderlabs/logspout#96]
The current docs have various port commands etc that point to port 8000, but this seems to have changed to port 80, on master at least. Could this be noted in the docs?

**Comment by guanxudong** [comment]
```
2015/07/02 07:36:36 loading and persisting routes in /mnt/routes
2015/07/02 07:36:36 logspout v2 serving http on :8000
```
From the stdout, I thought the logspout is listening on 8000, not 80...
And the README.md maybe misleading here:
```
$ docker run -d --name="logspout" \
    --volume=/var/run/docker.sock:/tmp/docker.sock \
    --publish=127.0.0.1:8000:80 \   # here
    gliderlabs/logspout
$ curl http://127.0.0.1:8000/logs
```

**Comment by mishak87** [comment]
Fixed with https://github.com/gliderlabs/logspout/pull/140
